use serde::Deserialize;
use std::env;
use std::fs;

// ---------------------------------------------------------------------------
// Manifest data structures
// ---------------------------------------------------------------------------

#[derive(Debug, Deserialize)]
struct Manifest {
    namespace: String,
    #[serde(default)]
    public: bool,
    schemas: Vec<ManifestSchema>,
}

#[derive(Debug, Deserialize)]
struct ManifestSchema {
    name: String,
    #[serde(rename = "type")]
    schema_type: String, // "singleton" | "collection"
    #[serde(default)]
    fields: Vec<ManifestField>,
}

#[derive(Debug, Deserialize)]
struct ManifestField {
    name: String,
    #[serde(rename = "type")]
    field_type: String,
    #[serde(default)]
    required: bool,
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/// Convert a snake_case or lowercase string to PascalCase.
/// "demo_counter" → "DemoCounter", "homepage" → "Homepage"
fn to_pascal_case(s: &str) -> String {
    s.split('_')
        .filter(|part| !part.is_empty())
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                None => String::new(),
                Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
            }
        })
        .collect()
}

/// Convert a schema name to its API path slug.
/// Underscores are replaced by hyphens: "demo_counter" → "demo-counter"
fn to_slug(s: &str) -> String {
    s.replace('_', "-")
}

/// Map a Plato field type + required flag to the appropriate Rust type string.
fn to_rust_type(field_type: &str, required: bool) -> String {
    match field_type {
        "string" => {
            if required {
                "String".to_string()
            } else {
                "Option<String>".to_string()
            }
        }
        "number" => {
            if required {
                "f64".to_string()
            } else {
                "Option<f64>".to_string()
            }
        }
        "boolean" => {
            if required {
                "bool".to_string()
            } else {
                "Option<bool>".to_string()
            }
        }
        "date" => {
            if required {
                "String".to_string()
            } else {
                "Option<String>".to_string()
            }
        }
        "media" => {
            if required {
                "String".to_string()
            } else {
                "Option<String>".to_string()
            }
        }
        "relation_one" => {
            if required {
                "String".to_string()
            } else {
                "Option<String>".to_string()
            }
        }
        // relation_many is always Vec<String> regardless of required
        "relation_many" => "Vec<String>".to_string(),
        // Unknown types fall back to serde_json::Value
        other => {
            eprintln!("warning: unknown field type '{}', mapping to serde_json::Value", other);
            if required {
                "serde_json::Value".to_string()
            } else {
                "Option<serde_json::Value>".to_string()
            }
        }
    }
}

/// Return true when a field's Rust type is wrapped in Option<_>.
fn is_optional_type(field_type: &str, required: bool) -> bool {
    if field_type == "relation_many" {
        return false;
    }
    !required
}

/// Return an inline comment for certain field types to clarify semantics.
fn field_type_comment(field_type: &str) -> Option<&'static str> {
    match field_type {
        "date" => Some("// ISO 8601 date string"),
        "media" => Some("// media asset URL"),
        "relation_one" => Some("// ID of related item"),
        "relation_many" => Some("// IDs of related items"),
        _ => None,
    }
}

// ---------------------------------------------------------------------------
// Code generation
// ---------------------------------------------------------------------------

/// Build the complete generated Rust client source as a single String.
fn generate(manifest: &Manifest) -> String {
    let mut out = String::new();

    // -----------------------------------------------------------------------
    // File header
    // -----------------------------------------------------------------------
    out.push_str("// Generated by plato-codegen. DO NOT EDIT.\n");
    out.push_str("// Regenerate with: plato-codegen [manifest] [output]\n");
    out.push_str("//\n");
    out.push_str("// To use this generated client, add to your Cargo.toml:\n");
    out.push_str("// [dependencies]\n");
    out.push_str("// serde = { version = \"1\", features = [\"derive\"] }\n");
    out.push_str("// serde_json = \"1\"\n");
    out.push_str("// reqwest = { version = \"0.12\", features = [\"blocking\", \"json\"] }\n");
    out.push('\n');
    out.push_str("#![allow(dead_code)]\n");
    out.push('\n');
    out.push_str("use serde::{Deserialize, Serialize};\n");
    out.push_str("use std::collections::HashMap;\n");
    out.push('\n');

    // -----------------------------------------------------------------------
    // PlatoItem base struct
    // -----------------------------------------------------------------------
    out.push_str("// ---------------------------------------------------------------------------\n");
    out.push_str("// Base item\n");
    out.push_str("// ---------------------------------------------------------------------------\n");
    out.push('\n');
    out.push_str("#[derive(Debug, Clone, Serialize, Deserialize)]\n");
    out.push_str("pub struct PlatoItem {\n");
    out.push_str("    pub id: String,\n");
    out.push_str("    pub created_at: String,\n");
    out.push_str("    pub updated_at: String,\n");
    out.push_str("}\n");
    out.push('\n');

    // -----------------------------------------------------------------------
    // One struct per schema
    // -----------------------------------------------------------------------
    out.push_str("// ---------------------------------------------------------------------------\n");
    out.push_str("// Schema structs\n");
    out.push_str("// ---------------------------------------------------------------------------\n");
    out.push('\n');

    for schema in &manifest.schemas {
        let struct_name = to_pascal_case(&schema.name);
        let is_singleton = schema.schema_type == "singleton";

        // Doc comment
        if is_singleton {
            out.push_str(&format!(
                "/// {} is a singleton.\n",
                struct_name
            ));
        } else {
            out.push_str(&format!(
                "/// {} is a collection item.\n",
                struct_name
            ));
        }

        out.push_str("#[derive(Debug, Clone, Serialize, Deserialize)]\n");
        out.push_str("#[serde(rename_all = \"snake_case\")]\n");
        out.push_str(&format!("pub struct {} {{\n", struct_name));

        // Flattened base fields
        out.push_str("    pub id: String,\n");
        out.push_str("    pub created_at: String,\n");
        out.push_str("    pub updated_at: String,\n");

        // Schema-specific fields
        for field in &schema.fields {
            let rust_type = to_rust_type(&field.field_type, field.required);
            let optional = is_optional_type(&field.field_type, field.required);
            let inline_comment = field_type_comment(&field.field_type);

            if optional {
                out.push_str("    #[serde(skip_serializing_if = \"Option::is_none\")]\n");
            }

            match inline_comment {
                Some(comment) => {
                    out.push_str(&format!(
                        "    pub {}: {}, {}\n",
                        field.name, rust_type, comment
                    ));
                }
                None => {
                    out.push_str(&format!("    pub {}: {},\n", field.name, rust_type));
                }
            }
        }

        out.push_str("}\n");
        out.push('\n');
    }

    // -----------------------------------------------------------------------
    // Params structs for collections
    // -----------------------------------------------------------------------
    let collections: Vec<&ManifestSchema> = manifest
        .schemas
        .iter()
        .filter(|s| s.schema_type == "collection")
        .collect();

    if !collections.is_empty() {
        out.push_str("// ---------------------------------------------------------------------------\n");
        out.push_str("// Query params structs (collections only)\n");
        out.push_str("// ---------------------------------------------------------------------------\n");
        out.push('\n');

        for schema in &collections {
            let struct_name = to_pascal_case(&schema.name);

            out.push_str(&format!(
                "/// Query parameters for filtering/searching {}.\n",
                struct_name
            ));
            out.push_str("#[derive(Debug, Default)]\n");
            out.push_str(&format!("pub struct {}Params {{\n", struct_name));

            for field in &schema.fields {
                out.push_str(&format!("    pub {}: Option<String>,\n", field.name));
            }

            out.push_str("}\n");
            out.push('\n');
        }
    }

    // -----------------------------------------------------------------------
    // PlatoClient struct
    // -----------------------------------------------------------------------
    out.push_str("// ---------------------------------------------------------------------------\n");
    out.push_str("// PlatoClient\n");
    out.push_str("// ---------------------------------------------------------------------------\n");
    out.push('\n');
    out.push_str("pub struct PlatoClient {\n");
    out.push_str("    base_url: String,\n");
    out.push_str("    namespace: String,\n");
    out.push_str("    api_key: Option<String>,\n");
    out.push_str("    client: reqwest::blocking::Client,\n");
    out.push_str("}\n");
    out.push('\n');

    // -----------------------------------------------------------------------
    // PlatoClient core impl
    // -----------------------------------------------------------------------
    out.push_str("impl PlatoClient {\n");

    // new()
    out.push_str("    /// Create a new PlatoClient.\n");
    out.push_str("    ///\n");
    out.push_str("    /// # Arguments\n");
    out.push_str("    /// * `base_url`  - The root URL of your Plato API, e.g. `\"https://api.plato.io\"`\n");
    out.push_str("    /// * `namespace` - The namespace declared in your manifest\n");
    out.push_str("    /// * `api_key`   - Optional API key for authenticated requests\n");
    out.push_str("    pub fn new(\n");
    out.push_str("        base_url: impl Into<String>,\n");
    out.push_str("        namespace: impl Into<String>,\n");
    out.push_str("        api_key: Option<impl Into<String>>,\n");
    out.push_str("    ) -> Self {\n");
    out.push_str("        Self {\n");
    out.push_str("            base_url: base_url.into().trim_end_matches('/').to_string(),\n");
    out.push_str("            namespace: namespace.into(),\n");
    out.push_str("            api_key: api_key.map(|k| k.into()),\n");
    out.push_str("            client: reqwest::blocking::Client::new(),\n");
    out.push_str("        }\n");
    out.push_str("    }\n");
    out.push('\n');

    // url()
    out.push_str("    fn url(&self, path: &str) -> String {\n");
    out.push_str("        format!(\"{}/api/{}/{}\", self.base_url, self.namespace, path.trim_start_matches('/'))\n");
    out.push_str("    }\n");
    out.push('\n');

    // headers()
    out.push_str("    fn headers(&self) -> reqwest::header::HeaderMap {\n");
    out.push_str("        let mut headers = reqwest::header::HeaderMap::new();\n");
    out.push_str("        headers.insert(\n");
    out.push_str("            reqwest::header::CONTENT_TYPE,\n");
    out.push_str("            reqwest::header::HeaderValue::from_static(\"application/json\"),\n");
    out.push_str("        );\n");
    out.push_str("        if let Some(key) = &self.api_key {\n");
    out.push_str("            if let Ok(val) = reqwest::header::HeaderValue::from_str(key) {\n");
    out.push_str("                headers.insert(\"x-api-key\", val);\n");
    out.push_str("            }\n");
    out.push_str("        }\n");
    out.push_str("        headers\n");
    out.push_str("    }\n");
    out.push('\n');

    // get()
    out.push_str("    fn get<T: for<'de> serde::Deserialize<'de>>(&self, path: &str) -> Result<T, reqwest::Error> {\n");
    out.push_str("        self.client\n");
    out.push_str("            .get(self.url(path))\n");
    out.push_str("            .headers(self.headers())\n");
    out.push_str("            .send()?\n");
    out.push_str("            .error_for_status()?\n");
    out.push_str("            .json::<T>()\n");
    out.push_str("    }\n");
    out.push('\n');

    // get_with_query()
    out.push_str("    fn get_with_query<T: for<'de> serde::Deserialize<'de>>(\n");
    out.push_str("        &self,\n");
    out.push_str("        path: &str,\n");
    out.push_str("        query: &[(String, String)],\n");
    out.push_str("    ) -> Result<T, reqwest::Error> {\n");
    out.push_str("        self.client\n");
    out.push_str("            .get(self.url(path))\n");
    out.push_str("            .headers(self.headers())\n");
    out.push_str("            .query(query)\n");
    out.push_str("            .send()?\n");
    out.push_str("            .error_for_status()?\n");
    out.push_str("            .json::<T>()\n");
    out.push_str("    }\n");
    out.push('\n');

    // post()
    out.push_str("    fn post<T: for<'de> serde::Deserialize<'de>>(\n");
    out.push_str("        &self,\n");
    out.push_str("        path: &str,\n");
    out.push_str("        body: &impl serde::Serialize,\n");
    out.push_str("    ) -> Result<T, reqwest::Error> {\n");
    out.push_str("        self.client\n");
    out.push_str("            .post(self.url(path))\n");
    out.push_str("            .headers(self.headers())\n");
    out.push_str("            .json(body)\n");
    out.push_str("            .send()?\n");
    out.push_str("            .error_for_status()?\n");
    out.push_str("            .json::<T>()\n");
    out.push_str("    }\n");
    out.push('\n');

    // put()
    out.push_str("    fn put<T: for<'de> serde::Deserialize<'de>>(\n");
    out.push_str("        &self,\n");
    out.push_str("        path: &str,\n");
    out.push_str("        body: &impl serde::Serialize,\n");
    out.push_str("    ) -> Result<T, reqwest::Error> {\n");
    out.push_str("        self.client\n");
    out.push_str("            .put(self.url(path))\n");
    out.push_str("            .headers(self.headers())\n");
    out.push_str("            .json(body)\n");
    out.push_str("            .send()?\n");
    out.push_str("            .error_for_status()?\n");
    out.push_str("            .json::<T>()\n");
    out.push_str("    }\n");
    out.push('\n');

    // delete()
    out.push_str("    fn delete(&self, path: &str) -> Result<(), reqwest::Error> {\n");
    out.push_str("        self.client\n");
    out.push_str("            .delete(self.url(path))\n");
    out.push_str("            .headers(self.headers())\n");
    out.push_str("            .send()?\n");
    out.push_str("            .error_for_status()?;\n");
    out.push_str("        Ok(())\n");
    out.push_str("    }\n");

    out.push_str("}\n");
    out.push('\n');

    // -----------------------------------------------------------------------
    // Per-schema methods
    // -----------------------------------------------------------------------
    out.push_str("// ---------------------------------------------------------------------------\n");
    out.push_str("// Schema-specific methods\n");
    out.push_str("// ---------------------------------------------------------------------------\n");
    out.push('\n');

    for schema in &manifest.schemas {
        let struct_name = to_pascal_case(&schema.name);
        let slug = to_slug(&schema.name);
        let is_singleton = schema.schema_type == "singleton";

        out.push_str("impl PlatoClient {\n");

        if is_singleton {
            // get_<name>
            out.push_str(&format!(
                "    /// Fetch the {} singleton.\n",
                schema.name
            ));
            out.push_str(&format!(
                "    pub fn get_{name}(&self) -> Result<Option<{Struct}>, reqwest::Error> {{\n",
                name = schema.name,
                Struct = struct_name,
            ));
            out.push_str(&format!(
                "        let items: Vec<{Struct}> = self.get(\"{slug}\")?;\n",
                Struct = struct_name,
                slug = slug,
            ));
            out.push_str("        Ok(items.into_iter().next())\n");
            out.push_str("    }\n");
            out.push('\n');

            // update_<name>
            out.push_str(&format!(
                "    /// Update the {} singleton.\n",
                schema.name
            ));
            out.push_str(&format!(
                "    pub fn update_{name}(\n",
                name = schema.name,
            ));
            out.push_str("        &self,\n");
            out.push_str("        data: &HashMap<String, serde_json::Value>,\n");
            out.push_str(&format!(
                "    ) -> Result<{Struct}, Box<dyn std::error::Error>> {{\n",
                Struct = struct_name,
            ));
            out.push_str(&format!(
                "        let item = self.get_{name}()?.ok_or(\"{slug} singleton not found\")?;\n",
                name = schema.name,
                slug = slug,
            ));
            out.push_str(&format!(
                "        Ok(self.put(&format!(\"{slug}/{{}}\", item.id), data)?)\n",
                slug = slug,
            ));
            out.push_str("    }\n");
        } else {
            // list_<name>
            out.push_str(&format!(
                "    /// List all {} items, with optional query filters.\n",
                schema.name
            ));
            out.push_str(&format!(
                "    pub fn list_{name}(\n",
                name = schema.name,
            ));
            out.push_str("        &self,\n");
            out.push_str(&format!(
                "        params: Option<{Struct}Params>,\n",
                Struct = struct_name,
            ));
            out.push_str(&format!(
                "    ) -> Result<Vec<{Struct}>, reqwest::Error> {{\n",
                Struct = struct_name,
            ));
            out.push_str("        let query: Vec<(String, String)> = params\n");
            out.push_str("            .map(|p| {\n");
            out.push_str("                let mut pairs: Vec<(String, String)> = Vec::new();\n");

            for field in &schema.fields {
                out.push_str(&format!(
                    "                if let Some(v) = p.{field} {{ pairs.push((\"{field}\".to_string(), v)); }}\n",
                    field = field.name,
                ));
            }

            out.push_str("                pairs\n");
            out.push_str("            })\n");
            out.push_str("            .unwrap_or_default();\n");
            out.push('\n');
            out.push_str("        if query.is_empty() {\n");
            out.push_str(&format!(
                "            self.get(\"{slug}\")\n",
                slug = slug,
            ));
            out.push_str("        } else {\n");
            out.push_str(&format!(
                "            self.get_with_query(\"{slug}\", &query)\n",
                slug = slug,
            ));
            out.push_str("        }\n");
            out.push_str("    }\n");
            out.push('\n');

            // get_<name>
            out.push_str(&format!(
                "    /// Fetch a single {} item by ID.\n",
                schema.name
            ));
            out.push_str(&format!(
                "    pub fn get_{name}(&self, id: &str) -> Result<{Struct}, reqwest::Error> {{\n",
                name = schema.name,
                Struct = struct_name,
            ));
            out.push_str(&format!(
                "        self.get(&format!(\"{slug}/{{}}\", id))\n",
                slug = slug,
            ));
            out.push_str("    }\n");
            out.push('\n');

            // create_<name>
            out.push_str(&format!(
                "    /// Create a new {} item.\n",
                schema.name
            ));
            out.push_str(&format!(
                "    pub fn create_{name}(\n",
                name = schema.name,
            ));
            out.push_str("        &self,\n");
            out.push_str("        data: &HashMap<String, serde_json::Value>,\n");
            out.push_str(&format!(
                "    ) -> Result<{Struct}, reqwest::Error> {{\n",
                Struct = struct_name,
            ));
            out.push_str(&format!(
                "        self.post(\"{slug}\", data)\n",
                slug = slug,
            ));
            out.push_str("    }\n");
            out.push('\n');

            // update_<name>
            out.push_str(&format!(
                "    /// Update an existing {} item by ID.\n",
                schema.name
            ));
            out.push_str(&format!(
                "    pub fn update_{name}(\n",
                name = schema.name,
            ));
            out.push_str("        &self,\n");
            out.push_str("        id: &str,\n");
            out.push_str("        data: &HashMap<String, serde_json::Value>,\n");
            out.push_str(&format!(
                "    ) -> Result<{Struct}, reqwest::Error> {{\n",
                Struct = struct_name,
            ));
            out.push_str(&format!(
                "        self.put(&format!(\"{slug}/{{}}\", id), data)\n",
                slug = slug,
            ));
            out.push_str("    }\n");
            out.push('\n');

            // delete_<name>
            out.push_str(&format!(
                "    /// Delete a {} item by ID.\n",
                schema.name
            ));
            out.push_str(&format!(
                "    pub fn delete_{name}(&self, id: &str) -> Result<(), reqwest::Error> {{\n",
                name = schema.name,
            ));
            out.push_str(&format!(
                "        self.delete(&format!(\"{slug}/{{}}\", id))\n",
                slug = slug,
            ));
            out.push_str("    }\n");
        }

        out.push_str("}\n");
        out.push('\n');
    }

    // -----------------------------------------------------------------------
    // Namespace constant
    // -----------------------------------------------------------------------
    out.push_str("// ---------------------------------------------------------------------------\n");
    out.push_str("// Manifest metadata\n");
    out.push_str("// ---------------------------------------------------------------------------\n");
    out.push('\n');
    out.push_str(&format!(
        "/// The namespace this client was generated from.\n"
    ));
    out.push_str(&format!(
        "pub const PLATO_NAMESPACE: &str = \"{}\";\n",
        manifest.namespace
    ));
    out.push('\n');
    out.push_str(&format!(
        "/// Whether the namespace is public (no API key required).\n"
    ));
    out.push_str(&format!(
        "pub const PLATO_PUBLIC: bool = {};\n",
        manifest.public
    ));
    out.push('\n');

    out
}

// ---------------------------------------------------------------------------
// main
// ---------------------------------------------------------------------------

fn main() {
    let args: Vec<String> = env::args().collect();

    let manifest_path = args.get(1).map(|s| s.as_str()).unwrap_or("plato-manifest.json");
    let output_path = args.get(2).map(|s| s.as_str()).unwrap_or("plato_client.rs");

    // Read and parse manifest
    let raw = fs::read_to_string(manifest_path).unwrap_or_else(|err| {
        eprintln!("error: could not read manifest '{}': {}", manifest_path, err);
        std::process::exit(1);
    });

    let manifest: Manifest = serde_json::from_str(&raw).unwrap_or_else(|err| {
        eprintln!("error: failed to parse manifest '{}': {}", manifest_path, err);
        std::process::exit(1);
    });

    // Generate output
    let code = generate(&manifest);

    // Write output
    fs::write(output_path, &code).unwrap_or_else(|err| {
        eprintln!("error: could not write output '{}': {}", output_path, err);
        std::process::exit(1);
    });

    println!(
        "Generated {} ({} schemas, namespace: {})",
        output_path,
        manifest.schemas.len(),
        manifest.namespace
    );
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_to_pascal_case_single_word() {
        assert_eq!(to_pascal_case("homepage"), "Homepage");
    }

    #[test]
    fn test_to_pascal_case_multi_word() {
        assert_eq!(to_pascal_case("demo_counter"), "DemoCounter");
    }

    #[test]
    fn test_to_pascal_case_triple_word() {
        assert_eq!(to_pascal_case("blog_post_tag"), "BlogPostTag");
    }

    #[test]
    fn test_to_slug() {
        assert_eq!(to_slug("demo_counter"), "demo-counter");
        assert_eq!(to_slug("homepage"), "homepage");
    }

    #[test]
    fn test_to_rust_type_required() {
        assert_eq!(to_rust_type("string", true), "String");
        assert_eq!(to_rust_type("number", true), "f64");
        assert_eq!(to_rust_type("boolean", true), "bool");
        assert_eq!(to_rust_type("date", true), "String");
        assert_eq!(to_rust_type("media", true), "String");
        assert_eq!(to_rust_type("relation_one", true), "String");
        assert_eq!(to_rust_type("relation_many", true), "Vec<String>");
    }

    #[test]
    fn test_to_rust_type_optional() {
        assert_eq!(to_rust_type("string", false), "Option<String>");
        assert_eq!(to_rust_type("number", false), "Option<f64>");
        assert_eq!(to_rust_type("boolean", false), "Option<bool>");
        assert_eq!(to_rust_type("date", false), "Option<String>");
        assert_eq!(to_rust_type("media", false), "Option<String>");
        assert_eq!(to_rust_type("relation_one", false), "Option<String>");
        // relation_many is always Vec<String>
        assert_eq!(to_rust_type("relation_many", false), "Vec<String>");
    }

    #[test]
    fn test_is_optional_type() {
        assert!(!is_optional_type("string", true));
        assert!(is_optional_type("string", false));
        assert!(!is_optional_type("relation_many", false));
        assert!(!is_optional_type("relation_many", true));
    }

    #[test]
    fn test_generate_contains_struct_names() {
        let manifest = Manifest {
            namespace: "website".to_string(),
            public: true,
            schemas: vec![
                ManifestSchema {
                    name: "homepage".to_string(),
                    schema_type: "singleton".to_string(),
                    fields: vec![ManifestField {
                        name: "hero_title".to_string(),
                        field_type: "string".to_string(),
                        required: true,
                    }],
                },
                ManifestSchema {
                    name: "post".to_string(),
                    schema_type: "collection".to_string(),
                    fields: vec![ManifestField {
                        name: "title".to_string(),
                        field_type: "string".to_string(),
                        required: true,
                    }],
                },
            ],
        };

        let code = generate(&manifest);

        assert!(code.contains("pub struct Homepage {"));
        assert!(code.contains("pub struct Post {"));
        assert!(code.contains("pub struct PostParams {"));
        assert!(code.contains("pub fn get_homepage("));
        assert!(code.contains("pub fn update_homepage("));
        assert!(code.contains("pub fn list_post("));
        assert!(code.contains("pub fn get_post("));
        assert!(code.contains("pub fn create_post("));
        assert!(code.contains("pub fn update_post("));
        assert!(code.contains("pub fn delete_post("));
        assert!(code.contains("pub const PLATO_NAMESPACE: &str = \"website\";"));
        assert!(code.contains("pub const PLATO_PUBLIC: bool = true;"));
    }

    #[test]
    fn test_generate_slug_with_underscore() {
        let manifest = Manifest {
            namespace: "test".to_string(),
            public: false,
            schemas: vec![ManifestSchema {
                name: "demo_counter".to_string(),
                schema_type: "collection".to_string(),
                fields: vec![],
            }],
        };

        let code = generate(&manifest);
        // The API path slug should use hyphens
        assert!(code.contains("\"demo-counter\""));
    }

    #[test]
    fn test_generate_relation_many_no_option() {
        let manifest = Manifest {
            namespace: "test".to_string(),
            public: true,
            schemas: vec![ManifestSchema {
                name: "post".to_string(),
                schema_type: "collection".to_string(),
                fields: vec![ManifestField {
                    name: "tags".to_string(),
                    field_type: "relation_many".to_string(),
                    required: false,
                }],
            }],
        };

        let code = generate(&manifest);
        // relation_many should always be Vec<String>, never Option<Vec<String>>
        assert!(code.contains("pub tags: Vec<String>"));
        assert!(!code.contains("Option<Vec<String>>"));
    }

    #[test]
    fn test_generate_header_comment() {
        let manifest = Manifest {
            namespace: "n".to_string(),
            public: false,
            schemas: vec![],
        };
        let code = generate(&manifest);
        assert!(code.contains("// Generated by plato-codegen. DO NOT EDIT."));
        assert!(code.contains("#![allow(dead_code)]"));
        assert!(code.contains("use serde::{Deserialize, Serialize};"));
        assert!(code.contains("use std::collections::HashMap;"));
    }
}
