# frozen_string_literal: true

require "fileutils"

# PlatoCodegen generates an idiomatic Ruby client from a parsed plato-manifest.json hash.
#
# Usage:
#   manifest = JSON.parse(File.read("plato-manifest.json"))
#   ruby_source = PlatoCodegen.generate(manifest)
#   File.write("plato_client.rb", ruby_source)
module PlatoCodegen
  # Map Plato field types to Ruby type documentation strings.
  RUBY_TYPE_MAP = {
    "string"       => "String",
    "number"       => "Numeric",
    "boolean"      => "TrueClass/FalseClass",
    "date"         => "String",
    "media"        => "String",
    "relation_one" => "String",
    "relation_many" => "Array<String>"
  }.freeze

  # Inline notes appended to @return comments.
  TYPE_NOTES = {
    "date"         => "ISO 8601 date string",
    "media"        => "media asset URL",
    "relation_one" => "ID of related item",
    "relation_many" => "IDs of related items"
  }.freeze

  # Entry point — accepts a parsed manifest hash and returns the full Ruby source string.
  #
  # @param manifest [Hash] parsed plato-manifest.json
  # @return [String] Ruby source code
  def self.generate(manifest)
    namespace = manifest["namespace"] || raise(ArgumentError, "manifest missing 'namespace'")
    schemas   = manifest["schemas"]   || raise(ArgumentError, "manifest missing 'schemas'")

    sections = []
    sections << file_header(namespace)
    sections << base_module_open
    sections << schemas.map { |s| generate_struct(s) }.join("\n")
    sections << client_class(schemas, namespace)
    sections << "end # module Plato\n"

    sections.join("\n")
  end

  # -------------------------------------------------------------------------
  # Naming helpers
  # -------------------------------------------------------------------------

  # Convert snake_case or kebab-case to PascalCase.
  #
  # @param str [String]
  # @return [String]
  def self.pascal_case(str)
    str.split(/[_\-]/).map(&:capitalize).join
  end

  # Convert a schema name to the API path slug (underscores → hyphens).
  #
  # @param name [String]
  # @return [String]
  def self.slug(name)
    name.tr("_", "-")
  end

  # Convert a schema name to snake_case method suffix (already snake_case from manifest).
  #
  # @param name [String]
  # @return [String]
  def self.method_name(name)
    name.tr("-", "_")
  end

  # -------------------------------------------------------------------------
  # Documentation helpers
  # -------------------------------------------------------------------------

  # Types that are inherently non-nil (always return a collection, not nil).
  ARRAY_TYPES = %w[relation_many].freeze

  # Return the Ruby type annotation string for a Plato field type.
  # Array types (relation_many) are never annotated as nilable — an empty
  # array is the zero value, not nil.
  #
  # @param field_type [String]
  # @param required [Boolean]
  # @return [String]
  def self.ruby_type_annotation(field_type, required: false)
    base = RUBY_TYPE_MAP.fetch(field_type, "Object")
    return base if required || ARRAY_TYPES.include?(field_type)

    "#{base}, nil"
  end

  # Return an inline trailing note for a field type, or empty string.
  #
  # @param field_type [String]
  # @return [String]
  def self.ruby_type_comment(field_type)
    note = TYPE_NOTES[field_type]
    note ? " #{note}" : ""
  end

  # -------------------------------------------------------------------------
  # Code section generators
  # -------------------------------------------------------------------------

  def self.file_header(namespace)
    <<~RUBY
      # frozen_string_literal: true
      # ============================================================
      # plato_client.rb — auto-generated by plato_codegen
      # namespace : #{namespace}
      # generated : #{Time.now.strftime("%Y-%m-%d")}
      #
      # DO NOT EDIT — re-run `ruby exe/plato-codegen` to regenerate.
      # ============================================================

      require "json"
      require "net/http"
      require "uri"
    RUBY
  end

  def self.base_module_open
    <<~RUBY
      module Plato
    RUBY
  end

  # Generate the Struct definition for a single schema.
  #
  # @param schema [Hash]
  # @return [String]
  def self.generate_struct(schema)
    name       = schema["name"]
    type       = schema["type"]  # "singleton" or "collection"
    fields     = schema["fields"] || []
    class_name = pascal_case(name)

    field_syms     = fields.map { |f| f["name"].to_sym }
    all_field_syms = ([:id, :created_at, :updated_at] + field_syms).map { |s| ":#{s}" }.join(", ")

    return_docs = fields.map do |field|
      fname     = field["name"]
      ftype     = field["type"] || "string"
      required  = field["required"] == true
      type_ann  = ruby_type_annotation(ftype, required: required)
      note      = ruby_type_comment(ftype)
      req_tag   = required ? " (required)" : ""
      "    # @return [#{type_ann}] #{fname}#{req_tag}#{note}"
    end.join("\n")

    <<~RUBY
        # #{type} — #{name}
        #{class_name} = Struct.new(#{all_field_syms}, keyword_init: true) do
      #{return_docs}
        end

    RUBY
  end

  # Generate the full Plato::Client class with all CRUD methods for every schema.
  #
  # @param schemas [Array<Hash>]
  # @param _namespace [String] kept for future use
  # @return [String]
  def self.client_class(schemas, _namespace)
    method_blocks = schemas.map { |s| generate_methods(s) }.join("\n")

    <<~RUBY
        # HTTP client for the Plato content API.
        class Client
          # @param base_url [String] Plato base URL (e.g. "http://localhost:6100")
          # @param namespace [String] namespace slug
          # @param api_key [String, nil] optional API key sent as a Bearer token
          def initialize(base_url, namespace, api_key = nil)
            @base_url  = base_url.chomp("/")
            @namespace = namespace
            @api_key   = api_key
          end

      #{method_blocks.gsub(/^/, "  ")}
          private

          def headers
            h = { "Content-Type" => "application/json", "Accept" => "application/json" }
            h["Authorization"] = "Bearer #{"\#{@api_key}"}" if @api_key
            h
          end

          def request(method, path, body = nil)
            uri  = URI("#{"\#{@base_url}"}/api/namespaces/#{"\#{@namespace}"}/content/#{"\#{path}"}")
            http = Net::HTTP.new(uri.host, uri.port)
            http.use_ssl = uri.scheme == "https"

            req = Net::HTTP.const_get(method.capitalize).new(uri)
            headers.each { |k, v| req[k] = v }
            req.body = body.to_json if body

            res = http.request(req)
            unless res.is_a?(Net::HTTPSuccess)
              raise "Plato #{"\#{method.upcase}"} #{"\#{uri}"}: #{"\#{res.code}"} #{"\#{res.message}"}"
            end

            res.body.empty? ? nil : JSON.parse(res.body, symbolize_names: true)
          end

          def get(path)    = request("get",    path)
          def post(path, body) = request("post",   path, body)
          def put(path, body)  = request("put",    path, body)
          def delete(path) = request("delete", path)
        end
    RUBY
  end

  # Generate public CRUD methods for a schema and inject them into Client.
  # Singletons get `get_<name>` and `update_<name>`.
  # Collections get `list_<name>`, `get_<name>`, `create_<name>`, `update_<name>`, `delete_<name>`.
  #
  # @param schema [Hash]
  # @return [String]
  def self.generate_methods(schema)
    name       = schema["name"]
    schema_type = schema["type"]
    class_name = pascal_case(name)
    mname      = method_name(name)
    api_slug   = slug(name)

    if schema_type == "singleton"
      generate_singleton_methods(class_name, mname, api_slug)
    else
      generate_collection_methods(class_name, mname, api_slug)
    end
  end

  def self.generate_singleton_methods(class_name, mname, api_slug)
    <<~RUBY
      # Fetch the #{mname} singleton.
      # @return [Plato::#{class_name}, nil]
      def get_#{mname}
        items = get("#{api_slug}")
        return nil if items.nil? || (items.is_a?(Array) && items.empty?)
        data = items.is_a?(Array) ? items.first : items
        #{class_name}.new(**data)
      end

      # Update the #{mname} singleton.
      # @param attrs [Hash] attributes to update
      # @return [Plato::#{class_name}]
      def update_#{mname}(attrs)
        item = get_#{mname} or raise "#{mname} singleton not found"
        #{class_name}.new(**put("#{api_slug}/\#{item.id}", attrs))
      end

    RUBY
  end

  def self.generate_collection_methods(class_name, mname, api_slug)
    <<~RUBY
      # List #{class_name} items.
      # @param params [Hash] optional filter/pagination params (e.g. { page: 1, per_page: 20 })
      # @return [Array<Plato::#{class_name}>]
      def list_#{mname}(params = {})
        qs    = params.empty? ? "" : "?\#{URI.encode_www_form(params)}"
        items = get("#{api_slug}\#{qs}")
        Array(items).map { |item| #{class_name}.new(**item) }
      end

      # Get a #{class_name} item by ID.
      # @param id [String]
      # @return [Plato::#{class_name}]
      def get_#{mname}(id)
        #{class_name}.new(**get("#{api_slug}/\#{id}"))
      end

      # Create a new #{class_name} item.
      # @param attrs [Hash] initial attributes
      # @return [Plato::#{class_name}]
      def create_#{mname}(attrs)
        #{class_name}.new(**post("#{api_slug}", attrs))
      end

      # Update a #{class_name} item.
      # @param id [String]
      # @param attrs [Hash] attributes to update
      # @return [Plato::#{class_name}]
      def update_#{mname}(id, attrs)
        #{class_name}.new(**put("#{api_slug}/\#{id}", attrs))
      end

      # Delete a #{class_name} item.
      # @param id [String]
      # @return [void]
      def delete_#{mname}(id)
        delete("#{api_slug}/\#{id}")
        nil
      end

    RUBY
  end

  private_class_method :file_header, :base_module_open, :generate_struct,
                       :client_class, :generate_singleton_methods,
                       :generate_collection_methods
end
