// Generated by plato-codegen. DO NOT EDIT.
// Regenerate with: plato-codegen [manifest] [output]
//
// To use this generated client, add to your Cargo.toml:
// [dependencies]
// serde = { version = "1", features = ["derive"] }
// serde_json = "1"
// reqwest = { version = "0.12", features = ["blocking", "json"] }

#![allow(dead_code)]

use serde::{Deserialize, Serialize};
use std::collections::HashMap;

// ---------------------------------------------------------------------------
// Base item
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PlatoItem {
    pub id: String,
    pub created_at: String,
    pub updated_at: String,
}

// ---------------------------------------------------------------------------
// Schema structs
// ---------------------------------------------------------------------------

/// Homepage is a singleton.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub struct Homepage {
    pub id: String,
    pub created_at: String,
    pub updated_at: String,
    pub hero_title: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub hero_subtitle: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub hero_image: Option<String>, // media asset URL
}

/// Post is a collection item.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub struct Post {
    pub id: String,
    pub created_at: String,
    pub updated_at: String,
    pub title: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub body: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub published_at: Option<String>, // ISO 8601 date string
    pub tags: Vec<String>, // IDs of related items
}

// ---------------------------------------------------------------------------
// Query params structs (collections only)
// ---------------------------------------------------------------------------

/// Query parameters for filtering/searching Post.
#[derive(Debug, Default)]
pub struct PostParams {
    pub title: Option<String>,
    pub body: Option<String>,
    pub published_at: Option<String>,
    pub tags: Option<String>,
}

// ---------------------------------------------------------------------------
// PlatoClient
// ---------------------------------------------------------------------------

pub struct PlatoClient {
    base_url: String,
    namespace: String,
    api_key: Option<String>,
    client: reqwest::blocking::Client,
}

impl PlatoClient {
    /// Create a new PlatoClient.
    ///
    /// # Arguments
    /// * `base_url`  - The root URL of your Plato API, e.g. `"https://api.plato.io"`
    /// * `namespace` - The namespace declared in your manifest
    /// * `api_key`   - Optional API key for authenticated requests
    pub fn new(
        base_url: impl Into<String>,
        namespace: impl Into<String>,
        api_key: Option<impl Into<String>>,
    ) -> Self {
        Self {
            base_url: base_url.into().trim_end_matches('/').to_string(),
            namespace: namespace.into(),
            api_key: api_key.map(|k| k.into()),
            client: reqwest::blocking::Client::new(),
        }
    }

    fn url(&self, path: &str) -> String {
        format!("{}/api/{}/{}", self.base_url, self.namespace, path.trim_start_matches('/'))
    }

    fn headers(&self) -> reqwest::header::HeaderMap {
        let mut headers = reqwest::header::HeaderMap::new();
        headers.insert(
            reqwest::header::CONTENT_TYPE,
            reqwest::header::HeaderValue::from_static("application/json"),
        );
        if let Some(key) = &self.api_key {
            if let Ok(val) = reqwest::header::HeaderValue::from_str(key) {
                headers.insert("x-api-key", val);
            }
        }
        headers
    }

    fn get<T: for<'de> serde::Deserialize<'de>>(&self, path: &str) -> Result<T, reqwest::Error> {
        self.client
            .get(self.url(path))
            .headers(self.headers())
            .send()?
            .error_for_status()?
            .json::<T>()
    }

    fn get_with_query<T: for<'de> serde::Deserialize<'de>>(
        &self,
        path: &str,
        query: &[(String, String)],
    ) -> Result<T, reqwest::Error> {
        self.client
            .get(self.url(path))
            .headers(self.headers())
            .query(query)
            .send()?
            .error_for_status()?
            .json::<T>()
    }

    fn post<T: for<'de> serde::Deserialize<'de>>(
        &self,
        path: &str,
        body: &impl serde::Serialize,
    ) -> Result<T, reqwest::Error> {
        self.client
            .post(self.url(path))
            .headers(self.headers())
            .json(body)
            .send()?
            .error_for_status()?
            .json::<T>()
    }

    fn put<T: for<'de> serde::Deserialize<'de>>(
        &self,
        path: &str,
        body: &impl serde::Serialize,
    ) -> Result<T, reqwest::Error> {
        self.client
            .put(self.url(path))
            .headers(self.headers())
            .json(body)
            .send()?
            .error_for_status()?
            .json::<T>()
    }

    fn delete(&self, path: &str) -> Result<(), reqwest::Error> {
        self.client
            .delete(self.url(path))
            .headers(self.headers())
            .send()?
            .error_for_status()?;
        Ok(())
    }
}

// ---------------------------------------------------------------------------
// Schema-specific methods
// ---------------------------------------------------------------------------

impl PlatoClient {
    /// Fetch the homepage singleton.
    pub fn get_homepage(&self) -> Result<Option<Homepage>, reqwest::Error> {
        let items: Vec<Homepage> = self.get("homepage")?;
        Ok(items.into_iter().next())
    }

    /// Update the homepage singleton.
    pub fn update_homepage(
        &self,
        data: &HashMap<String, serde_json::Value>,
    ) -> Result<Homepage, Box<dyn std::error::Error>> {
        let item = self.get_homepage()?.ok_or("homepage singleton not found")?;
        Ok(self.put(&format!("homepage/{}", item.id), data)?)
    }
}

impl PlatoClient {
    /// List all post items, with optional query filters.
    pub fn list_post(
        &self,
        params: Option<PostParams>,
    ) -> Result<Vec<Post>, reqwest::Error> {
        let query: Vec<(String, String)> = params
            .map(|p| {
                let mut pairs: Vec<(String, String)> = Vec::new();
                if let Some(v) = p.title { pairs.push(("title".to_string(), v)); }
                if let Some(v) = p.body { pairs.push(("body".to_string(), v)); }
                if let Some(v) = p.published_at { pairs.push(("published_at".to_string(), v)); }
                if let Some(v) = p.tags { pairs.push(("tags".to_string(), v)); }
                pairs
            })
            .unwrap_or_default();

        if query.is_empty() {
            self.get("post")
        } else {
            self.get_with_query("post", &query)
        }
    }

    /// Fetch a single post item by ID.
    pub fn get_post(&self, id: &str) -> Result<Post, reqwest::Error> {
        self.get(&format!("post/{}", id))
    }

    /// Create a new post item.
    pub fn create_post(
        &self,
        data: &HashMap<String, serde_json::Value>,
    ) -> Result<Post, reqwest::Error> {
        self.post("post", data)
    }

    /// Update an existing post item by ID.
    pub fn update_post(
        &self,
        id: &str,
        data: &HashMap<String, serde_json::Value>,
    ) -> Result<Post, reqwest::Error> {
        self.put(&format!("post/{}", id), data)
    }

    /// Delete a post item by ID.
    pub fn delete_post(&self, id: &str) -> Result<(), reqwest::Error> {
        self.delete(&format!("post/{}", id))
    }
}

// ---------------------------------------------------------------------------
// Manifest metadata
// ---------------------------------------------------------------------------

/// The namespace this client was generated from.
pub const PLATO_NAMESPACE: &str = "website";

/// Whether the namespace is public (no API key required).
pub const PLATO_PUBLIC: bool = true;

