// Generated by @platoorg/ts-client — run `npx plato-ts generate` to regenerate
// Namespace: website · public: true

// ── Media ──────────────────────────────────────────────────
/**
 * Build src / srcset / sizes attributes from a Plato media value.
 * Returns null when no usable URL is present.
 */
export function mediaSrcset(value, sizes) {
  if (value == null) return null;
  if (typeof value === 'string') return value ? { src: value } : null;
  if (!value.url && !value.variants) return null;

  const entries = [];
  let maxWidth = 0;
  if (value.variants) {
    for (const raw of Object.values(value.variants)) {
      if (!raw || typeof raw !== 'object') continue;
      const { url, width } = raw;
      if (!url || !width || width <= 0) continue;
      entries.push({ url, width });
      if (width > maxWidth) maxWidth = width;
    }
  }

  const dims = {};
  if (typeof value.width === 'number')  dims.width  = value.width;
  if (typeof value.height === 'number') dims.height = value.height;

  if (entries.length === 0) {
    return value.url ? { src: value.url, ...dims } : null;
  }

  if (value.url) {
    const w = (value.width ?? 0) > maxWidth ? value.width : maxWidth + 1;
    entries.push({ url: value.url, width: w });
  }
  entries.sort((a, b) => a.width - b.width);

  const srcset = entries.map(e => `${e.url} ${e.width}w`).join(', ');
  return {
    src: value.url || entries[entries.length - 1].url,
    srcset,
    ...(sizes ? { sizes } : {}),
    ...dims,
  };
}

export class PlatoClient {
  #baseUrl;
  #namespace;
  #apiKey;

  constructor(baseUrl, namespace, apiKey) {
    this.#baseUrl    = baseUrl;
    this.#namespace  = namespace;
    this.#apiKey     = apiKey;
  }

  static fromEnv() {
    const url = process.env['PLATO_URL'];
    const ns  = process.env['PLATO_NAMESPACE'];
    if (!url) throw new Error('[plato] PLATO_URL env var is not set');
    if (!ns)  throw new Error('[plato] PLATO_NAMESPACE env var is not set');
    return new PlatoClient(url, ns, process.env['PLATO_API_KEY']);
  }

  #headers() {
    const h = { 'Content-Type': 'application/json' };
    if (this.#apiKey) h['Authorization'] = `Bearer ${this.#apiKey}`;
    return h;
  }

  async #request(path, init) {
    const url = `${this.#baseUrl}/api/namespaces/${this.#namespace}/content/${path}`;
    const res = await fetch(url, { ...init, headers: this.#headers() });
    if (!res.ok) throw new Error(`Plato ${init?.method ?? 'GET'} ${url}: ${res.status} ${res.statusText}`);
    return res.json();
  }

  #buildQs(filters, populate) {
    const pairs = Object.entries(filters).filter(([, v]) => v != null);
    const qs = new URLSearchParams(pairs.map(([k, v]) => [k, String(v)]));
    if (populate?.length) qs.set('populate', populate.join(','));
    const s = qs.toString();
    return s ? '?' + s : '';
  }

  #get(path)        { return this.#request(path); }
  #post(path, body) { return this.#request(path, { method: 'POST', body: JSON.stringify(body) }); }
  #put(path, body)  { return this.#request(path, { method: 'PUT',  body: JSON.stringify(body) }); }

  // ── Generic ─────────────────────────────────────────────────
  /** Fetch a singleton by schema slug — typed escape hatch for unlisted schemas. */
  async getSingleton(schema) {
    return this.#get(schema);
  }

  /** Fetch a collection by schema slug — typed escape hatch for unlisted schemas. */
  async getCollection(schema, params) {
    return this.#get(`${schema}${this.#buildQs(params ?? {})}`);
  }

  // ── homepage (singleton) ────────────────────────────────────
  /** Fetch the homepage singleton. */
  async getHomepage() {
    return this.#get('homepage');
  }

  /** Update the homepage singleton. */
  async updateHomepage(data) {
    return this.#put('homepage', data);
  }

  /** Like getHomepage() but returns null instead of throwing on error. */
  async tryGetHomepage() {
    try { return await this.getHomepage(); } catch { return null; }
  }

  // ── post (collection) ────────────────────────────────────────
  /** List post items. Supports filtering and server-side relation population. */
  async listPost(params) {
    const { populate, ...filters } = params ?? {};
    return this.#get(`post${this.#buildQs(filters, populate)}`);
  }

  /** Fetch a single post item by ID. */
  async getPost(id) {
    return this.#get(`post/${id}`);
  }

  /** Create a new post item. */
  async createPost(data) {
    return this.#post('post', data);
  }

  /** Update an existing post item. */
  async updatePost(id, data) {
    return this.#put(`post/${id}`, data);
  }

  /** Delete a post item. */
  async deletePost(id) {
    await this.#request(`post/${id}`, { method: 'DELETE' });
  }

  /** Return the first post matching the given params, or null. */
  async findPost(params) {
    const results = await this.listPost(params);
    return results[0] ?? null;
  }

  /** Like listPost() but returns [] instead of throwing on error. */
  async tryListPost(params) {
    try { return await this.listPost(params); } catch { return []; }
  }

  /** Like getPost() but returns null instead of throwing on error. */
  async tryGetPost(id) {
    try { return await this.getPost(id); } catch { return null; }
  }

  // ── article (collection) ─────────────────────────────────────
  /** List article items. Supports filtering and server-side relation population. */
  async listArticle(params) {
    const { populate, ...filters } = params ?? {};
    return this.#get(`article${this.#buildQs(filters, populate)}`);
  }

  /** Fetch a single article item by ID. */
  async getArticle(id) {
    return this.#get(`article/${id}`);
  }

  /** Create a new article item. */
  async createArticle(data) {
    return this.#post('article', data);
  }

  /** Update an existing article item. */
  async updateArticle(id, data) {
    return this.#put(`article/${id}`, data);
  }

  /** Delete a article item. */
  async deleteArticle(id) {
    await this.#request(`article/${id}`, { method: 'DELETE' });
  }

  /** Return the first article matching the given params, or null. */
  async findArticle(params) {
    const results = await this.listArticle(params);
    return results[0] ?? null;
  }

  /** Like listArticle() but returns [] instead of throwing on error. */
  async tryListArticle(params) {
    try { return await this.listArticle(params); } catch { return []; }
  }

  /** Like getArticle() but returns null instead of throwing on error. */
  async tryGetArticle(id) {
    try { return await this.getArticle(id); } catch { return null; }
  }
}
