// Generated by @platoorg/ts-client — run `npx plato-ts generate` to regenerate
// Namespace: website · public: true

export interface PlatoItem {
  id: string;
  created_at: string;
  updated_at: string;
}

/** singleton */
export interface Homepage extends PlatoItem {
  hero_title: string;
  hero_subtitle?: string;
  hero_image?: string; // media asset URL
}

/** collection */
export interface Post extends PlatoItem {
  title: string;
  body?: string;
  published_at?: string; // ISO 8601 date string
  tags?: string[]; // IDs of related items
}

export declare class PlatoClient {
  constructor(baseUrl: string, namespace: string, apiKey?: string);
  static fromEnv(): PlatoClient;
  /** Fetch homepage (singleton) */
  fetchSchema(schema: 'homepage'): Promise<Homepage>;
  /** Fetch post (collection) */
  fetchSchema(schema: 'post'): Promise<Post[]>;
  fetchSchema(schema: string): Promise<PlatoItem | PlatoItem[]>;
  /** Fetch any content item by its ID */
  fetchContent(id: string): Promise<PlatoItem>;
}
