// Generated by @platoorg/ts-client — run `npx plato-ts generate` to regenerate
// Namespace: website · public: true

const SCHEMA_META = {
  'homepage': { slug: 'homepage', singleton: true },
  'post': { slug: 'post', singleton: false },
};

export class PlatoClient {
  #baseUrl;
  #namespace;
  #apiKey;

  constructor(baseUrl, namespace, apiKey) {
    this.#baseUrl    = baseUrl;
    this.#namespace  = namespace;
    this.#apiKey     = apiKey;
  }

  #headers() {
    const h = { 'Content-Type': 'application/json' };
    if (this.#apiKey) h['Authorization'] = `Bearer ${this.#apiKey}`;
    return h;
  }

  async #request(path, init) {
    const url = `${this.#baseUrl}/api/namespaces/${this.#namespace}/content/${path}`;
    const res = await fetch(url, { ...init, headers: this.#headers() });
    if (!res.ok) throw new Error(`Plato ${init?.method ?? 'GET'} ${url}: ${res.status} ${res.statusText}`);
    return res.json();
  }

  async fetchSchema(schema) {
    const meta = SCHEMA_META[schema];
    if (!meta) throw new Error(`[plato] Unknown schema: "${schema}". Known: ${Object.keys(SCHEMA_META).join(", ")}`);
    return this.#request(meta.slug);
  }

  async fetchContent(id) {
    return this.#request(id);
  }
}
