// Generated by @platoorg/ts-client — run `npx plato-ts generate` to regenerate
// Namespace: website · public: true

// ── Media ──────────────────────────────────────────────────
/** A single resized variant generated at upload time. */
export interface MediaVariant {
  url: string;
  width: number;
}
/**
 * Stored value for a `media` field. Plato writes the new shape
 * ({url, width, height, variants: {name: {url, width}}}); the legacy
 * shape used variants: {name: "url-string"} and is still tolerated by
 * mediaSrcset() but produces no srcset (widths are unknown).
 */
export interface MediaValue {
  url: string;
  width?: number;
  height?: number;
  variants?: Record<string, MediaVariant | string>;
}
/** Result of mediaSrcset(). Spread into <img {...result} alt="..." />. */
export interface MediaSrcsetResult {
  src: string;
  srcset?: string;
  sizes?: string;
  width?: number;
  height?: number;
}
/**
 * Build src / srcset / sizes attributes from a Plato media value.
 * Returns null when no usable URL is present.
 */
export declare function mediaSrcset(
  value: MediaValue | string | null | undefined,
  sizes?: string,
): MediaSrcsetResult | null;

export interface PlatoItem {
  id: string;
  created_at: string;
  updated_at: string;
}

/** singleton */
export interface Homepage extends PlatoItem {
  hero_title: string;
  hero_subtitle?: string;
  hero_image?: MediaValue | string;
}

/** collection */
export interface Post extends PlatoItem {
  title: string;
  body?: string;
  published_at?: string; // ISO 8601 date string
  tags?: string[]; // IDs of related items
}

/** collection */
export interface Article extends PlatoItem {
  title: string;
  body?: string;
  meta_description?: string;
  cover_image?: MediaValue | string;
  og_title?: string;
  author?: string;
}

export interface PostParams {
  title?: string;
  body?: string;
  published_at?: string;
  tags?: string;
  /** Relation fields to populate server-side (e.g. ["tags", "author"]). */
  populate?: string[];
}

export interface ArticleParams {
  title?: string;
  body?: string;
  meta_description?: string;
  cover_image?: string;
  og_title?: string;
  author?: string;
  /** Relation fields to populate server-side (e.g. ["tags", "author"]). */
  populate?: string[];
}

export declare class PlatoClient {
  constructor(baseUrl: string, namespace: string, apiKey?: string);
  static fromEnv(): PlatoClient;
  /** Fetch a singleton by schema slug — typed escape hatch for unlisted schemas. */
  getSingleton<T extends PlatoItem>(schema: string): Promise<T>;
  /** Fetch a collection by schema slug — typed escape hatch for unlisted schemas. */
  getCollection<T extends PlatoItem>(schema: string, params?: Record<string, string | number | boolean>): Promise<T[]>;

  // ── homepage (singleton) ────────────────────────────────────
  getHomepage(): Promise<Homepage>;
  updateHomepage(data: Partial<Omit<Homepage, keyof PlatoItem>>): Promise<Homepage>;
  tryGetHomepage(): Promise<Homepage | null>;

  // ── post (collection) ────────────────────────────────────────
  listPost(params?: PostParams): Promise<Post[]>;
  getPost(id: string): Promise<Post>;
  createPost(data: Omit<Post, keyof PlatoItem>): Promise<Post>;
  updatePost(id: string, data: Partial<Omit<Post, keyof PlatoItem>>): Promise<Post>;
  deletePost(id: string): Promise<void>;
  findPost(params: PostParams): Promise<Post | null>;
  tryListPost(params?: PostParams): Promise<Post[]>;
  tryGetPost(id: string): Promise<Post | null>;

  // ── article (collection) ─────────────────────────────────────
  listArticle(params?: ArticleParams): Promise<Article[]>;
  getArticle(id: string): Promise<Article>;
  createArticle(data: Omit<Article, keyof PlatoItem>): Promise<Article>;
  updateArticle(id: string, data: Partial<Omit<Article, keyof PlatoItem>>): Promise<Article>;
  deleteArticle(id: string): Promise<void>;
  findArticle(params: ArticleParams): Promise<Article | null>;
  tryListArticle(params?: ArticleParams): Promise<Article[]>;
  tryGetArticle(id: string): Promise<Article | null>;
}
