// Generated by @platoorg/ts-client — run `npx plato-ts generate` to regenerate
// Namespace: website · public: true

export interface PlatoItem {
  id: string;
  created_at: string;
  updated_at: string;
}

/** singleton */
export interface Homepage extends PlatoItem {
  hero_title: string;
  hero_subtitle?: string;
  hero_image?: string; // media asset URL
}

/** collection */
export interface Post extends PlatoItem {
  title: string;
  body?: string;
  published_at?: string; // ISO 8601 date string
  tags?: string[]; // IDs of related items
}

export interface PostParams {
  title?: string;
  body?: string;
  published_at?: string;
  tags?: string;
  /** Relation fields to populate server-side (e.g. ["tags", "author"]). */
  populate?: string[];
}

export declare class PlatoClient {
  constructor(baseUrl: string, namespace: string, apiKey?: string);
  static fromEnv(): PlatoClient;
  /** Fetch a singleton by schema slug — typed escape hatch for unlisted schemas. */
  getSingleton<T extends PlatoItem>(schema: string): Promise<T>;
  /** Fetch a collection by schema slug — typed escape hatch for unlisted schemas. */
  getCollection<T extends PlatoItem>(schema: string, params?: Record<string, string | number | boolean>): Promise<T[]>;

  // ── homepage (singleton) ────────────────────────────────────
  getHomepage(): Promise<Homepage>;
  updateHomepage(data: Partial<Omit<Homepage, keyof PlatoItem>>): Promise<Homepage>;
  tryGetHomepage(): Promise<Homepage | null>;

  // ── post (collection) ────────────────────────────────────────
  listPost(params?: PostParams): Promise<Post[]>;
  getPost(id: string): Promise<Post>;
  createPost(data: Omit<Post, keyof PlatoItem>): Promise<Post>;
  updatePost(id: string, data: Partial<Omit<Post, keyof PlatoItem>>): Promise<Post>;
  deletePost(id: string): Promise<void>;
  findPost(params: PostParams): Promise<Post | null>;
  tryListPost(params?: PostParams): Promise<Post[]>;
  tryGetPost(id: string): Promise<Post | null>;
}
