defmodule PlatoCodegen.CLI do
  @moduledoc """
  Entry point for the plato_codegen escript.

  Usage:
      ./plato_codegen [manifest_path] [output_path]

  Defaults:
      manifest_path -> plato-manifest.json
      output_path   -> plato_client.ex
  """

  def main(args) do
    {manifest_path, output_path} =
      case args do
        [] -> {"plato-manifest.json", "plato_client.ex"}
        [m] -> {m, "plato_client.ex"}
        [m, o | _] -> {m, o}
      end

    with {:read, {:ok, raw}} <- {:read, File.read(manifest_path)},
         {:parse, {:ok, manifest}} <- {:parse, parse_json(raw)},
         {:gen, source} <- {:gen, PlatoCodegen.generate(manifest)},
         {:write, :ok} <- {:write, File.write(output_path, source)} do
      IO.puts("Generated #{output_path} from #{manifest_path}")
    else
      {:read, {:error, reason}} ->
        IO.puts(:stderr, "Error reading manifest '#{manifest_path}': #{:file.format_error(reason)}")
        System.halt(1)

      {:parse, {:error, reason}} ->
        IO.puts(:stderr, "Error parsing JSON in '#{manifest_path}': #{inspect(reason)}")
        System.halt(1)

      {:write, {:error, reason}} ->
        IO.puts(:stderr, "Error writing '#{output_path}': #{:file.format_error(reason)}")
        System.halt(1)
    end
  end

  # ---------------------------------------------------------------------------
  # JSON parsing — uses :json (OTP 27+)
  # ---------------------------------------------------------------------------

  defp parse_json(raw) when is_binary(raw) do
    try do
      decoded = :json.decode(raw)
      {:ok, atomise_keys(decoded)}
    rescue
      e -> {:error, Exception.message(e)}
    catch
      kind, value -> {:error, {kind, value}}
    end
  end

  # Recursively convert map string keys to atoms (safe — keys come from a
  # controlled schema document, not arbitrary user input).
  defp atomise_keys(map) when is_map(map) do
    Map.new(map, fn {k, v} -> {String.to_atom(k), atomise_keys(v)} end)
  end

  defp atomise_keys(list) when is_list(list), do: Enum.map(list, &atomise_keys/1)
  defp atomise_keys(value), do: value
end

# =============================================================================

defmodule PlatoCodegen do
  @moduledoc """
  Generates an idiomatic Elixir client from a Plato manifest map.

  Call `generate/1` with the parsed manifest and receive the full Elixir
  source string back.
  """

  # ---------------------------------------------------------------------------
  # Public API
  # ---------------------------------------------------------------------------

  @doc """
  Accepts a manifest map (with atom keys) and returns the generated Elixir
  source code as a string.
  """
  @spec generate(map()) :: String.t()
  def generate(manifest) do
    namespace = Map.fetch!(manifest, :namespace)
    schemas = Map.get(manifest, :schemas, [])

    sections =
      [
        file_header(manifest),
        client_module(namespace),
        Enum.map(schemas, &schema_module/1),
        client_functions_module(schemas)
      ]
      |> List.flatten()

    Enum.join(sections, "\n")
  end

  # ---------------------------------------------------------------------------
  # File-level header
  # ---------------------------------------------------------------------------

  defp file_header(manifest) do
    namespace = Map.fetch!(manifest, :namespace)

    """
    # Generated by plato_codegen — do not edit by hand.
    # Namespace: #{namespace}
    # Generated at: #{DateTime.utc_now() |> DateTime.to_iso8601()}
    #
    # Requirements: Elixir 1.16+ / OTP 27+

    """
  end

  # ---------------------------------------------------------------------------
  # PlatoClient base module (config struct + constructor)
  # ---------------------------------------------------------------------------

  defp client_module(_namespace) do
    """
    defmodule PlatoClient do
      @moduledoc \"\"\"
      Configuration struct for the Plato HTTP client.

      ## Fields

        * `:base_url` - Base URL of the Plato API (e.g. `"https://api.plato.io"`).
        * `:namespace` - Namespace string that prefixes every API path.
        * `:api_key`   - Bearer token used for authentication. Pass `nil` for
                         unauthenticated (public) namespaces.

      ## Example

          client = PlatoClient.new("https://api.plato.io", "website", "secret-key")
          {:ok, homepage} = PlatoClient.get_homepage(client)

      \"\"\"

      @enforce_keys [:base_url, :namespace]

      defstruct [
        :base_url,
        :namespace,
        :api_key
      ]

      @type t :: %__MODULE__{
              base_url: String.t(),
              namespace: String.t(),
              api_key: String.t() | nil
            }

      @doc \"\"\"
      Creates a new `PlatoClient` configuration struct.

      ## Parameters

        * `base_url`  - Base URL of the Plato API.
        * `namespace` - Namespace string.
        * `api_key`   - Optional API key / bearer token.

      \"\"\"
      @spec new(String.t(), String.t(), String.t() | nil) :: t()
      def new(base_url, namespace, api_key \\\\ nil) do
        %__MODULE__{base_url: base_url, namespace: namespace, api_key: api_key}
      end

    """
  end

  # ---------------------------------------------------------------------------
  # Per-schema data modules
  # ---------------------------------------------------------------------------

  defp schema_module(schema) do
    name = Map.fetch!(schema, :name)
    fields = Map.get(schema, :fields, [])
    mod_name = module_name(name)

    system_fields = [
      {"id", "String.t()", true},
      {"created_at", "String.t()", true},
      {"updated_at", "String.t()", true}
    ]

    user_fields =
      Enum.map(fields, fn f ->
        fname = Map.fetch!(f, :name)
        ftype = Map.fetch!(f, :type)
        required = Map.get(f, :required, false)
        {fname, elixir_type(ftype, required), required}
      end)

    all_fields = system_fields ++ user_fields

    typespec_lines =
      all_fields
      |> Enum.map(fn {fname, ftype, _required} ->
        "              #{fname}: #{ftype}"
      end)
      |> Enum.join(",\n")

    struct_fields =
      all_fields
      |> Enum.map(fn {fname, _ftype, required} ->
        if required do
          "      :#{fname}"
        else
          "      #{fname}: nil"
        end
      end)
      |> Enum.join(",\n")

    enforce_keys =
      all_fields
      |> Enum.filter(fn {_fname, _ftype, required} -> required end)
      |> Enum.map(fn {fname, _ftype, _required} -> ":#{fname}" end)
      |> Enum.join(", ")

    from_map_assignments =
      all_fields
      |> Enum.map(fn {fname, ftype, _required} ->
        converter = from_map_converter(ftype, fname)
        "      #{fname}: #{converter}"
      end)
      |> Enum.join(",\n")

    """
      defmodule #{mod_name} do
        @moduledoc \"\"\"
        Struct representing the `#{name}` Plato schema.
        \"\"\"

        @enforce_keys [#{enforce_keys}]

        defstruct [
    #{struct_fields}
        ]

        @type t :: %__MODULE__{
    #{typespec_lines}
              }

        @doc \"\"\"
        Converts a raw map (as returned from JSON decoding) into a `#{mod_name}` struct.
        String keys and atom keys are both accepted.
        \"\"\"
        @spec from_map(map()) :: t()
        def from_map(map) do
          get = fn m, k ->
            case Map.fetch(m, k) do
              {:ok, v} -> v
              :error -> Map.get(m, Atom.to_string(k))
            end
          end

          %__MODULE__{
    #{from_map_assignments}
          }
        end
      end

    """
  end

  # ---------------------------------------------------------------------------
  # PlatoClient functions (CRUD) + private HTTP helpers, closing the module
  # ---------------------------------------------------------------------------

  defp client_functions_module(schemas) do
    function_blocks = Enum.map(schemas, &schema_functions/1)

    closing = """
      # ---------------------------------------------------------------------------
      # Private HTTP helpers
      # ---------------------------------------------------------------------------

      @doc false
      defp request(client, method, path, body \\\\ nil) do
        # Start inets/httpc if not already running; ignore :already_started.
        case :inets.start() do
          :ok -> :ok
          {:error, {:already_started, _}} -> :ok
        end

        url =
          (client.base_url <> "/" <> client.namespace <> path)
          |> String.to_charlist()

        headers = build_headers(client)

        result =
          case method do
            :get ->
              :httpc.request(:get, {url, headers}, [], [])

            :delete ->
              :httpc.request(:delete, {url, headers}, [], [])

            write_method when write_method in [:post, :put, :patch] ->
              json_body = encode_json(body || %{})
              content_type = ~c"application/json"
              :httpc.request(
                write_method,
                {url, headers, content_type, json_body},
                [],
                []
              )
          end

        case result do
          {:ok, {{_version, status, _phrase}, _headers, response_body}} ->
            body_binary =
              if is_list(response_body),
                do: List.to_string(response_body),
                else: response_body

            cond do
              status in 200..299 ->
                {:ok, body_binary}

              true ->
                {:error, {:http_error, status, body_binary}}
            end

          {:error, reason} ->
            {:error, reason}
        end
      end

      @doc false
      defp build_headers(client) do
        base = [
          {~c"accept", ~c"application/json"},
          {~c"content-type", ~c"application/json"}
        ]

        if client.api_key do
          [{~c"authorization", ~c"Bearer " ++ String.to_charlist(client.api_key)} | base]
        else
          base
        end
      end

      @doc false
      defp decode_json(binary) do
        try do
          {:ok, :json.decode(binary)}
        rescue
          e -> {:error, Exception.message(e)}
        catch
          kind, value -> {:error, {kind, value}}
        end
      end

      @doc false
      defp encode_json(value) do
        value
        |> :json.encode()
        |> IO.iodata_to_binary()
      end

      @doc false
      defp query_string([]), do: ""

      defp query_string(params) do
        encoded =
          params
          |> Enum.map(fn {k, v} ->
            key = URI.encode_www_form(to_string(k))
            val = URI.encode_www_form(to_string(v))
            key <> "=" <> val
          end)
          |> Enum.join("&")

        "?" <> encoded
      end
    end
    """

    [function_blocks, closing]
  end

  # ---------------------------------------------------------------------------
  # Per-schema function generation
  # ---------------------------------------------------------------------------

  defp schema_functions(schema) do
    name = Map.fetch!(schema, :name)
    schema_type = Map.fetch!(schema, :type)
    mod_name = module_name(name)
    slug = String.replace(name, "_", "-")

    case schema_type do
      "singleton" -> singleton_functions(name, mod_name, slug)
      "collection" -> collection_functions(name, mod_name, slug)
      other -> raise ArgumentError, "Unknown schema type: #{inspect(other)}"
    end
  end

  defp singleton_functions(name, mod_name, slug) do
    """
      # ---------------------------------------------------------------------------
      # #{mod_name} (singleton)
      # ---------------------------------------------------------------------------

      @doc \"\"\"
      Fetches the `#{name}` singleton from the Plato API.
      \"\"\"
      @spec get_#{name}(t()) :: {:ok, #{mod_name}.t()} | {:error, term()}
      def get_#{name}(client) do
        with {:ok, body} <- request(client, :get, "/#{slug}"),
             {:ok, data} <- decode_json(body) do
          {:ok, #{mod_name}.from_map(data)}
        end
      end

      @doc \"\"\"
      Updates the `#{name}` singleton on the Plato API.

      `attrs` is a map of fields to update. Only the provided keys are changed.
      \"\"\"
      @spec update_#{name}(t(), map()) :: {:ok, #{mod_name}.t()} | {:error, term()}
      def update_#{name}(client, attrs) do
        with {:ok, body} <- request(client, :patch, "/#{slug}", attrs),
             {:ok, data} <- decode_json(body) do
          {:ok, #{mod_name}.from_map(data)}
        end
      end

    """
  end

  defp collection_functions(name, mod_name, slug) do
    """
      # ---------------------------------------------------------------------------
      # #{mod_name} (collection)
      # ---------------------------------------------------------------------------

      @doc \"\"\"
      Lists all `#{name}` records from the Plato API.

      `params` is an optional keyword list of query parameters (e.g.
      `[page: 1, per_page: 20]`).
      \"\"\"
      @spec list_#{name}(t(), keyword()) :: {:ok, list(#{mod_name}.t())} | {:error, term()}
      def list_#{name}(client, params \\\\ []) do
        path = "/#{slug}" <> query_string(params)

        with {:ok, body} <- request(client, :get, path),
             {:ok, data} <- decode_json(body) do
          records =
            data
            |> List.wrap()
            |> Enum.map(&#{mod_name}.from_map/1)

          {:ok, records}
        end
      end

      @doc \"\"\"
      Fetches a single `#{name}` record by `id`.
      \"\"\"
      @spec get_#{name}(t(), String.t()) :: {:ok, #{mod_name}.t()} | {:error, term()}
      def get_#{name}(client, id) do
        with {:ok, body} <- request(client, :get, "/#{slug}/\#{id}"),
             {:ok, data} <- decode_json(body) do
          {:ok, #{mod_name}.from_map(data)}
        end
      end

      @doc \"\"\"
      Creates a new `#{name}` record on the Plato API.
      \"\"\"
      @spec create_#{name}(t(), map()) :: {:ok, #{mod_name}.t()} | {:error, term()}
      def create_#{name}(client, attrs) do
        with {:ok, body} <- request(client, :post, "/#{slug}", attrs),
             {:ok, data} <- decode_json(body) do
          {:ok, #{mod_name}.from_map(data)}
        end
      end

      @doc \"\"\"
      Updates an existing `#{name}` record identified by `id`.
      \"\"\"
      @spec update_#{name}(t(), String.t(), map()) :: {:ok, #{mod_name}.t()} | {:error, term()}
      def update_#{name}(client, id, attrs) do
        with {:ok, body} <- request(client, :patch, "/#{slug}/\#{id}", attrs),
             {:ok, data} <- decode_json(body) do
          {:ok, #{mod_name}.from_map(data)}
        end
      end

      @doc \"\"\"
      Deletes the `#{name}` record identified by `id`.
      \"\"\"
      @spec delete_#{name}(t(), String.t()) :: :ok | {:error, term()}
      def delete_#{name}(client, id) do
        case request(client, :delete, "/#{slug}/\#{id}") do
          {:ok, _body} -> :ok
          {:error, reason} -> {:error, reason}
        end
      end

    """
  end

  # ---------------------------------------------------------------------------
  # Helper utilities
  # ---------------------------------------------------------------------------

  # Converts a schema name like "demo_counter" to "DemoCounter"
  defp module_name(name) do
    name
    |> String.split("_")
    |> Enum.map(&String.capitalize/1)
    |> Enum.join()
    |> then(&"PlatoClient.#{&1}")
  end

  # Maps Plato field types to Elixir typespec strings
  defp elixir_type(plato_type, required) do
    base =
      case plato_type do
        "string" -> "String.t()"
        "number" -> "float()"
        "boolean" -> "boolean()"
        "date" -> "String.t()"
        "media" -> "String.t()"
        "relation_one" -> "String.t()"
        "relation_many" -> "list(String.t())"
        other -> raise ArgumentError, "Unknown Plato field type: #{inspect(other)}"
      end

    if required, do: base, else: "#{base} | nil"
  end

  # Returns the Elixir expression used in from_map/1 to extract and coerce a
  # field value. Uses the `get` closure defined inside from_map/1.
  defp from_map_converter(full_type, field_name) do
    # Strip the "| nil" suffix to get the base type string for pattern matching
    base_type =
      full_type
      |> String.replace(" | nil", "")
      |> String.trim()

    case base_type do
      "list(String.t())" ->
        # relation_many — ensure we have a list, default to []
        "case get.(map, :#{field_name}) do nil -> []; v when is_list(v) -> Enum.map(v, &to_string/1); v -> [to_string(v)] end"

      "float()" ->
        # number — coerce integers from JSON to float
        "case get.(map, :#{field_name}) do nil -> nil; v when is_integer(v) -> v * 1.0; v -> v end"

      _ ->
        "get.(map, :#{field_name})"
    end
  end
end
