# Generated by plato_codegen — do not edit by hand.
# Namespace: website
# Generated at: 2026-03-06T08:43:34.125381Z
#
# Requirements: Elixir 1.16+ / OTP 27+


defmodule PlatoClient do
  @moduledoc """
  Configuration struct for the Plato HTTP client.

  ## Fields

    * `:base_url` - Base URL of the Plato API (e.g. `"https://api.plato.io"`).
    * `:namespace` - Namespace string that prefixes every API path.
    * `:api_key`   - Bearer token used for authentication. Pass `nil` for
                     unauthenticated (public) namespaces.

  ## Example

      client = PlatoClient.new("https://api.plato.io", "website", "secret-key")
      {:ok, homepage} = PlatoClient.get_homepage(client)

  """

  @enforce_keys [:base_url, :namespace]

  defstruct [
    :base_url,
    :namespace,
    :api_key
  ]

  @type t :: %__MODULE__{
          base_url: String.t(),
          namespace: String.t(),
          api_key: String.t() | nil
        }

  @doc """
  Creates a new `PlatoClient` configuration struct.

  ## Parameters

    * `base_url`  - Base URL of the Plato API.
    * `namespace` - Namespace string.
    * `api_key`   - Optional API key / bearer token.

  """
  @spec new(String.t(), String.t(), String.t() | nil) :: t()
  def new(base_url, namespace, api_key \\ nil) do
    %__MODULE__{base_url: base_url, namespace: namespace, api_key: api_key}
  end


  defmodule PlatoClient.Homepage do
    @moduledoc """
    Struct representing the `homepage` Plato schema.
    """

    @enforce_keys [:id, :created_at, :updated_at, :hero_title]

    defstruct [
      :id,
      :created_at,
      :updated_at,
      :hero_title,
      hero_subtitle: nil,
      hero_image: nil
    ]

    @type t :: %__MODULE__{
              id: String.t(),
              created_at: String.t(),
              updated_at: String.t(),
              hero_title: String.t(),
              hero_subtitle: String.t() | nil,
              hero_image: String.t() | nil
          }

    @doc """
    Converts a raw map (as returned from JSON decoding) into a `PlatoClient.Homepage` struct.
    String keys and atom keys are both accepted.
    """
    @spec from_map(map()) :: t()
    def from_map(map) do
      get = fn m, k ->
        case Map.fetch(m, k) do
          {:ok, v} -> v
          :error -> Map.get(m, Atom.to_string(k))
        end
      end

      %__MODULE__{
      id: get.(map, :id),
      created_at: get.(map, :created_at),
      updated_at: get.(map, :updated_at),
      hero_title: get.(map, :hero_title),
      hero_subtitle: get.(map, :hero_subtitle),
      hero_image: get.(map, :hero_image)
      }
    end
  end


  defmodule PlatoClient.Post do
    @moduledoc """
    Struct representing the `post` Plato schema.
    """

    @enforce_keys [:id, :created_at, :updated_at, :title]

    defstruct [
      :id,
      :created_at,
      :updated_at,
      :title,
      body: nil,
      published_at: nil,
      tags: nil
    ]

    @type t :: %__MODULE__{
              id: String.t(),
              created_at: String.t(),
              updated_at: String.t(),
              title: String.t(),
              body: String.t() | nil,
              published_at: String.t() | nil,
              tags: list(String.t()) | nil
          }

    @doc """
    Converts a raw map (as returned from JSON decoding) into a `PlatoClient.Post` struct.
    String keys and atom keys are both accepted.
    """
    @spec from_map(map()) :: t()
    def from_map(map) do
      get = fn m, k ->
        case Map.fetch(m, k) do
          {:ok, v} -> v
          :error -> Map.get(m, Atom.to_string(k))
        end
      end

      %__MODULE__{
      id: get.(map, :id),
      created_at: get.(map, :created_at),
      updated_at: get.(map, :updated_at),
      title: get.(map, :title),
      body: get.(map, :body),
      published_at: get.(map, :published_at),
      tags: case get.(map, :tags) do nil -> []; v when is_list(v) -> Enum.map(v, &to_string/1); v -> [to_string(v)] end
      }
    end
  end


  # ---------------------------------------------------------------------------
  # PlatoClient.Homepage (singleton)
  # ---------------------------------------------------------------------------

  @doc """
  Fetches the `homepage` singleton from the Plato API.
  """
  @spec get_homepage(t()) :: {:ok, PlatoClient.Homepage.t()} | {:error, term()}
  def get_homepage(client) do
    with {:ok, body} <- request(client, :get, "/homepage"),
         {:ok, data} <- decode_json(body) do
      {:ok, PlatoClient.Homepage.from_map(data)}
    end
  end

  @doc """
  Updates the `homepage` singleton on the Plato API.

  `attrs` is a map of fields to update. Only the provided keys are changed.
  """
  @spec update_homepage(t(), map()) :: {:ok, PlatoClient.Homepage.t()} | {:error, term()}
  def update_homepage(client, attrs) do
    with {:ok, body} <- request(client, :patch, "/homepage", attrs),
         {:ok, data} <- decode_json(body) do
      {:ok, PlatoClient.Homepage.from_map(data)}
    end
  end


  # ---------------------------------------------------------------------------
  # PlatoClient.Post (collection)
  # ---------------------------------------------------------------------------

  @doc """
  Lists all `post` records from the Plato API.

  `params` is an optional keyword list of query parameters (e.g.
  `[page: 1, per_page: 20]`).
  """
  @spec list_post(t(), keyword()) :: {:ok, list(PlatoClient.Post.t())} | {:error, term()}
  def list_post(client, params \\ []) do
    path = "/post" <> query_string(params)

    with {:ok, body} <- request(client, :get, path),
         {:ok, data} <- decode_json(body) do
      records =
        data
        |> List.wrap()
        |> Enum.map(&PlatoClient.Post.from_map/1)

      {:ok, records}
    end
  end

  @doc """
  Fetches a single `post` record by `id`.
  """
  @spec get_post(t(), String.t()) :: {:ok, PlatoClient.Post.t()} | {:error, term()}
  def get_post(client, id) do
    with {:ok, body} <- request(client, :get, "/post/#{id}"),
         {:ok, data} <- decode_json(body) do
      {:ok, PlatoClient.Post.from_map(data)}
    end
  end

  @doc """
  Creates a new `post` record on the Plato API.
  """
  @spec create_post(t(), map()) :: {:ok, PlatoClient.Post.t()} | {:error, term()}
  def create_post(client, attrs) do
    with {:ok, body} <- request(client, :post, "/post", attrs),
         {:ok, data} <- decode_json(body) do
      {:ok, PlatoClient.Post.from_map(data)}
    end
  end

  @doc """
  Updates an existing `post` record identified by `id`.
  """
  @spec update_post(t(), String.t(), map()) :: {:ok, PlatoClient.Post.t()} | {:error, term()}
  def update_post(client, id, attrs) do
    with {:ok, body} <- request(client, :patch, "/post/#{id}", attrs),
         {:ok, data} <- decode_json(body) do
      {:ok, PlatoClient.Post.from_map(data)}
    end
  end

  @doc """
  Deletes the `post` record identified by `id`.
  """
  @spec delete_post(t(), String.t()) :: :ok | {:error, term()}
  def delete_post(client, id) do
    case request(client, :delete, "/post/#{id}") do
      {:ok, _body} -> :ok
      {:error, reason} -> {:error, reason}
    end
  end


  # ---------------------------------------------------------------------------
  # Private HTTP helpers
  # ---------------------------------------------------------------------------

  @doc false
  defp request(client, method, path, body \\ nil) do
    # Start inets/httpc if not already running; ignore :already_started.
    case :inets.start() do
      :ok -> :ok
      {:error, {:already_started, _}} -> :ok
    end

    url =
      (client.base_url <> "/" <> client.namespace <> path)
      |> String.to_charlist()

    headers = build_headers(client)

    result =
      case method do
        :get ->
          :httpc.request(:get, {url, headers}, [], [])

        :delete ->
          :httpc.request(:delete, {url, headers}, [], [])

        write_method when write_method in [:post, :put, :patch] ->
          json_body = encode_json(body || %{})
          content_type = ~c"application/json"
          :httpc.request(
            write_method,
            {url, headers, content_type, json_body},
            [],
            []
          )
      end

    case result do
      {:ok, {{_version, status, _phrase}, _headers, response_body}} ->
        body_binary =
          if is_list(response_body),
            do: List.to_string(response_body),
            else: response_body

        cond do
          status in 200..299 ->
            {:ok, body_binary}

          true ->
            {:error, {:http_error, status, body_binary}}
        end

      {:error, reason} ->
        {:error, reason}
    end
  end

  @doc false
  defp build_headers(client) do
    base = [
      {~c"accept", ~c"application/json"},
      {~c"content-type", ~c"application/json"}
    ]

    if client.api_key do
      [{~c"authorization", ~c"Bearer " ++ String.to_charlist(client.api_key)} | base]
    else
      base
    end
  end

  @doc false
  defp decode_json(binary) do
    try do
      {:ok, :json.decode(binary)}
    rescue
      e -> {:error, Exception.message(e)}
    catch
      kind, value -> {:error, {kind, value}}
    end
  end

  @doc false
  defp encode_json(value) do
    value
    |> :json.encode()
    |> IO.iodata_to_binary()
  end

  @doc false
  defp query_string([]), do: ""

  defp query_string(params) do
    encoded =
      params
      |> Enum.map(fn {k, v} ->
        key = URI.encode_www_form(to_string(k))
        val = URI.encode_www_form(to_string(v))
        key <> "=" <> val
      end)
      |> Enum.join("&")

    "?" <> encoded
  end
end
