// Code generated by plato-codegen — do not edit.

package plato

import (
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"
)

// PlatoItem is embedded in every Plato content struct.
type PlatoItem struct {
	ID        string `json:"id"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

// Homepage is a singleton.
type Homepage struct {
	PlatoItem
	HeroTitle    string  `json:"hero_title"`
	HeroSubtitle *string `json:"hero_subtitle,omitempty"`
	HeroImage    *string `json:"hero_image,omitempty"` // media asset URL
}

// Post is a collection item.
type Post struct {
	PlatoItem
	Title       string   `json:"title"`
	Body        *string  `json:"body,omitempty"`
	PublishedAt *string  `json:"published_at,omitempty"` // ISO 8601
	Tags        []string `json:"tags"` // IDs of related items
}

// PostParams holds optional filter parameters for ListPost.
type PostParams struct {
	Title       *string
	Body        *string
	PublishedAt *string
	Tags        *string
}

// PlatoClient communicates with a Plato REST API.
type PlatoClient struct {
	baseURL   string
	namespace string
	apiKey    string
	http      *http.Client
}

// NewPlatoClient creates a new PlatoClient.
// Pass an empty string for apiKey if the namespace is public.
func NewPlatoClient(baseURL, namespace, apiKey string) *PlatoClient {
	return &PlatoClient{
		baseURL:   strings.TrimRight(baseURL, "/"),
		namespace: namespace,
		apiKey:    apiKey,
		http:      &http.Client{Timeout: 30 * time.Second},
	}
}

// headers returns the HTTP headers required for every request.
func (c *PlatoClient) headers() map[string]string {
	h := map[string]string{
		"Content-Type": "application/json",
	}
	if c.apiKey != "" {
		h["Authorization"] = "Bearer " + c.apiKey
	}
	return h
}

// request executes an HTTP request and returns the raw response body.
// It returns an error for any non-2xx status code.
func (c *PlatoClient) request(method, path string, body any) ([]byte, error) {
	fullURL := c.baseURL + "/api/" + c.namespace + "/" + path

	var reqBody io.Reader
	if body != nil {
		encoded, err := json.Marshal(body)
		if err != nil {
			return nil, fmt.Errorf("plato: marshal request body: %w", err)
		}
		reqBody = strings.NewReader(string(encoded))
	}

	req, err := http.NewRequest(method, fullURL, reqBody)
	if err != nil {
		return nil, fmt.Errorf("plato: build request: %w", err)
	}

	for k, v := range c.headers() {
		req.Header.Set(k, v)
	}

	resp, err := c.http.Do(req)
	if err != nil {
		return nil, fmt.Errorf("plato: execute request: %w", err)
	}
	defer resp.Body.Close()

	data, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("plato: read response body: %w", err)
	}

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		return nil, fmt.Errorf("plato: unexpected status %d: %s", resp.StatusCode, string(data))
	}

	return data, nil
}

func (c *PlatoClient) get(path string) ([]byte, error) {
	return c.request(http.MethodGet, path, nil)
}

func (c *PlatoClient) post(path string, body any) ([]byte, error) {
	return c.request(http.MethodPost, path, body)
}

func (c *PlatoClient) put(path string, body any) ([]byte, error) {
	return c.request(http.MethodPut, path, body)
}

func (c *PlatoClient) delete(path string) error {
	_, err := c.request(http.MethodDelete, path, nil)
	return err
}

// GetHomepage fetches the homepage singleton.
func (c *PlatoClient) GetHomepage() (*Homepage, error) {
	data, err := c.get("homepage")
	if err != nil {
		return nil, err
	}
	var items []Homepage
	if err := json.Unmarshal(data, &items); err != nil {
		return nil, err
	}
	if len(items) == 0 {
		return nil, nil
	}
	return &items[0], nil
}

// UpdateHomepage updates the homepage singleton.
func (c *PlatoClient) UpdateHomepage(update map[string]any) (*Homepage, error) {
	item, err := c.GetHomepage()
	if err != nil {
		return nil, err
	}
	if item == nil {
		return nil, fmt.Errorf("homepage singleton not found")
	}
	data, err := c.put("homepage/"+item.ID, update)
	if err != nil {
		return nil, err
	}
	var result Homepage
	return &result, json.Unmarshal(data, &result)
}

// ListPost returns post items, optionally filtered.
func (c *PlatoClient) ListPost(params *PostParams) ([]Post, error) {
	path := "post"
	if params != nil {
		q := url.Values{}
		if params.Title != nil {
			q.Set("title", *params.Title)
		}
		if params.Body != nil {
			q.Set("body", *params.Body)
		}
		if params.PublishedAt != nil {
			q.Set("published_at", *params.PublishedAt)
		}
		if params.Tags != nil {
			q.Set("tags", *params.Tags)
		}
		if encoded := q.Encode(); encoded != "" {
			path += "?" + encoded
		}
	}
	data, err := c.get(path)
	if err != nil {
		return nil, err
	}
	var items []Post
	return items, json.Unmarshal(data, &items)
}

// GetPost fetches a single Post by ID.
func (c *PlatoClient) GetPost(id string) (*Post, error) {
	data, err := c.get("post/" + id)
	if err != nil {
		return nil, err
	}
	var item Post
	return &item, json.Unmarshal(data, &item)
}

// CreatePost creates a new Post.
func (c *PlatoClient) CreatePost(data map[string]any) (*Post, error) {
	respData, err := c.post("post", data)
	if err != nil {
		return nil, err
	}
	var item Post
	return &item, json.Unmarshal(respData, &item)
}

// UpdatePost updates an existing Post by ID.
func (c *PlatoClient) UpdatePost(id string, data map[string]any) (*Post, error) {
	respData, err := c.put("post/"+id, data)
	if err != nil {
		return nil, err
	}
	var item Post
	return &item, json.Unmarshal(respData, &item)
}

// DeletePost deletes a Post by ID.
func (c *PlatoClient) DeletePost(id string) error {
	return c.delete("post/" + id)
}

