# frozen_string_literal: true
# ============================================================
# plato_client.rb — auto-generated by plato_codegen
# namespace : website
# generated : 2026-03-06
#
# DO NOT EDIT — re-run `ruby exe/plato-codegen` to regenerate.
# ============================================================

require "json"
require "net/http"
require "uri"

module Plato

  # singleton — homepage
  Homepage = Struct.new(:id, :created_at, :updated_at, :hero_title, :hero_subtitle, :hero_image, keyword_init: true) do
    # @return [String] hero_title (required)
    # @return [String, nil] hero_subtitle
    # @return [String, nil] hero_image media asset URL
  end


  # collection — post
  Post = Struct.new(:id, :created_at, :updated_at, :title, :body, :published_at, :tags, keyword_init: true) do
    # @return [String] title (required)
    # @return [String, nil] body
    # @return [String, nil] published_at ISO 8601 date string
    # @return [Array<String>] tags IDs of related items
  end


  # HTTP client for the Plato content API.
  class Client
    # @param base_url [String] Plato base URL (e.g. "http://localhost:6100")
    # @param namespace [String] namespace slug
    # @param api_key [String, nil] optional API key sent as a Bearer token
    def initialize(base_url, namespace, api_key = nil)
      @base_url  = base_url.chomp("/")
      @namespace = namespace
      @api_key   = api_key
    end

  # Fetch the homepage singleton.
  # @return [Plato::Homepage, nil]
  def get_homepage
    items = get("homepage")
    return nil if items.nil? || (items.is_a?(Array) && items.empty?)
    data = items.is_a?(Array) ? items.first : items
    Homepage.new(**data)
  end
  
  # Update the homepage singleton.
  # @param attrs [Hash] attributes to update
  # @return [Plato::Homepage]
  def update_homepage(attrs)
    item = get_homepage or raise "homepage singleton not found"
    Homepage.new(**put("homepage/#{item.id}", attrs))
  end
  
  
  # List Post items.
  # @param params [Hash] optional filter/pagination params (e.g. { page: 1, per_page: 20 })
  # @return [Array<Plato::Post>]
  def list_post(params = {})
    qs    = params.empty? ? "" : "?#{URI.encode_www_form(params)}"
    items = get("post#{qs}")
    Array(items).map { |item| Post.new(**item) }
  end
  
  # Get a Post item by ID.
  # @param id [String]
  # @return [Plato::Post]
  def get_post(id)
    Post.new(**get("post/#{id}"))
  end
  
  # Create a new Post item.
  # @param attrs [Hash] initial attributes
  # @return [Plato::Post]
  def create_post(attrs)
    Post.new(**post("post", attrs))
  end
  
  # Update a Post item.
  # @param id [String]
  # @param attrs [Hash] attributes to update
  # @return [Plato::Post]
  def update_post(id, attrs)
    Post.new(**put("post/#{id}", attrs))
  end
  
  # Delete a Post item.
  # @param id [String]
  # @return [void]
  def delete_post(id)
    delete("post/#{id}")
    nil
  end
  

    private

    def headers
      h = { "Content-Type" => "application/json", "Accept" => "application/json" }
      h["Authorization"] = "Bearer #{@api_key}" if @api_key
      h
    end

    def request(method, path, body = nil)
      uri  = URI("#{@base_url}/api/namespaces/#{@namespace}/content/#{path}")
      http = Net::HTTP.new(uri.host, uri.port)
      http.use_ssl = uri.scheme == "https"

      req = Net::HTTP.const_get(method.capitalize).new(uri)
      headers.each { |k, v| req[k] = v }
      req.body = body.to_json if body

      res = http.request(req)
      unless res.is_a?(Net::HTTPSuccess)
        raise "Plato #{method.upcase} #{uri}: #{res.code} #{res.message}"
      end

      res.body.empty? ? nil : JSON.parse(res.body, symbolize_names: true)
    end

    def get(path)    = request("get",    path)
    def post(path, body) = request("post",   path, body)
    def put(path, body)  = request("put",    path, body)
    def delete(path) = request("delete", path)
  end

end # module Plato
