// Generated by plato-codegen — do not edit manually
// Namespace: website · public: true
// Schema count: 2

// ── Base ────────────────────────────────────────────────────
export interface PlatoItem {
  id: string;
  created_at: string;
  updated_at: string;
}

/** singleton */
export interface Homepage extends PlatoItem {
  hero_title: string;
  hero_subtitle?: string;
  hero_image?: string; // media asset URL
}

/** collection */
export interface Post extends PlatoItem {
  title: string;
  body?: string;
  published_at?: string; // ISO 8601 date string
  tags?: string[]; // IDs of related items
}

export interface PostParams {
  title?: string;
  body?: string;
  published_at?: string;
  tags?: string;
}

// ── Client ──────────────────────────────────────────────────
export class PlatoClient {
  constructor(
    private readonly baseUrl: string,
    private readonly namespace: string,
    private readonly apiKey?: string,
  ) {}

  private headers(): Record<string, string> {
    const h: Record<string, string> = { 'Content-Type': 'application/json' };
    if (this.apiKey) h['Authorization'] = `Bearer ${this.apiKey}`;
    return h;
  }

  private async request<T>(path: string, init?: RequestInit): Promise<T> {
    const url = `${this.baseUrl}/api/namespaces/${this.namespace}/content/${path}`;
    const res  = await fetch(url, { ...init, headers: this.headers() });
    if (!res.ok) {
      throw new Error(`Plato ${init?.method ?? 'GET'} ${url}: ${res.status} ${res.statusText}`);
    }
    return res.json() as Promise<T>;
  }

  private get<T>(path: string)                         { return this.request<T>(path); }
  private post<T>(path: string, body: unknown)         { return this.request<T>(path, { method: 'POST',   body: JSON.stringify(body) }); }
  private put<T>(path: string, body: unknown)          { return this.request<T>(path, { method: 'PUT',    body: JSON.stringify(body) }); }

  // ── homepage (singleton) ────────────────────────────────────
  /** Fetch the homepage singleton. */
  async getHomepage(): Promise<Homepage | null> {
    const data = await this.get<Homepage[]>('homepage');
    return data[0] ?? null;
  }

  /** Update the homepage singleton. */
  async updateHomepage(data: Partial<Omit<Homepage, keyof PlatoItem>>): Promise<Homepage> {
    const item = await this.getHomepage();
    if (!item) throw new Error('homepage singleton not found');
    return this.put<Homepage>(`homepage/${item.id}`, data);
  }

  // ── post (collection) ────────────────────────────────────────
  /** List post items. Pass filter params as `{ field: value }`. */
  async listPost(params?: PostParams): Promise<Post[]> {
    const qs = params ? '?' + new URLSearchParams(params as Record<string, string>) : '';
    return this.get<Post[]>(`post${qs}`);
  }

  /** Fetch a single post item by ID. */
  async getPost(id: string): Promise<Post> {
    return this.get<Post>(`post/${id}`);
  }

  /** Create a new post item. */
  async createPost(data: Omit<Post, keyof PlatoItem>): Promise<Post> {
    return this.post<Post>('post', data);
  }

  /** Update an existing post item. */
  async updatePost(id: string, data: Partial<Omit<Post, keyof PlatoItem>>): Promise<Post> {
    return this.put<Post>(`post/${id}`, data);
  }

  /** Delete a post item. */
  async deletePost(id: string): Promise<void> {
    await this.request(`post/${id}`, { method: 'DELETE' });
  }
}
