// Generated by plato-codegen-zod — do not edit manually
// Namespace: website · public: true
// Schema count: 2

import { z } from 'zod';

// ── Base ─────────────────────────────────────────────────────
export const PlatoItemSchema = z.object({
  id: z.string(),
  created_at: z.string().optional(),
  updated_at: z.string().optional(),
});
export type PlatoItem = z.infer<typeof PlatoItemSchema>;

/** singleton */
export const HomepageSchema = PlatoItemSchema.extend({
  hero_title: z.string(),
  hero_subtitle: z.string().optional(),
  hero_image: z.string().url().optional(), // media asset URL
});
export type Homepage = z.infer<typeof HomepageSchema>;

/** collection */
export const PostSchema = PlatoItemSchema.extend({
  title: z.string(),
  body: z.string().optional(),
  published_at: z.string().optional(), // ISO 8601 date string
  tags: z.array(z.string()).optional(), // IDs of related items
});
export type Post = z.infer<typeof PostSchema>;

export interface PostParams {
  title?: string;
  body?: string;
  published_at?: string;
  tags?: string;
}

// ── Client ──────────────────────────────────────────────────
export class PlatoClient {
  constructor(
    private readonly baseUrl: string,
    private readonly namespace: string,
    private readonly apiKey?: string,
  ) {}

  private headers(): Record<string, string> {
    const h: Record<string, string> = { 'Content-Type': 'application/json' };
    if (this.apiKey) h['Authorization'] = `Bearer ${this.apiKey}`;
    return h;
  }

  private async request<T>(path: string, init?: RequestInit): Promise<T> {
    const url = `${this.baseUrl}/api/namespaces/${this.namespace}/content/${path}`;
    const res  = await fetch(url, { ...init, headers: this.headers() });
    if (!res.ok) {
      throw new Error(`Plato ${init?.method ?? 'GET'} ${url}: ${res.status} ${res.statusText}`);
    }
    return res.json() as Promise<T>;
  }

  private parse<T>(schema: z.ZodType<T>, data: unknown, label: string): T {
    try {
      return schema.parse(data);
    } catch (err) {
      if (err instanceof z.ZodError) {
        const issues = err.errors.map(e => `${e.path.join('.')||'root'}: ${e.message}`).join('; ');
        throw new Error(`PlatoParseError [${label}]: ${issues}`);
      }
      throw err;
    }
  }

  // ── homepage (singleton) ────────────────────────────────────
  /** Fetch the homepage singleton. */
  async getHomepage(): Promise<Homepage | null> {
    const data = await this.request<unknown>('homepage');
    const items = this.parse(z.array(HomepageSchema), data, 'Homepage[]');
    return items[0] ?? null;
  }

  /** Update the homepage singleton. */
  async updateHomepage(data: Partial<Omit<Homepage, keyof PlatoItem>>): Promise<Homepage> {
    const item = await this.getHomepage();
    if (!item) throw new Error('homepage singleton not found');
    const result = await this.request<unknown>(`homepage/${item.id}`, {
      method: 'PUT',
      body: JSON.stringify(data),
    });
    return this.parse(HomepageSchema, result, 'Homepage');
  }

  // ── post (collection) ────────────────────────────────────────
  /** List post items. Pass filter params as `{ field: value }`. */
  async listPost(params?: PostParams): Promise<Post[]> {
    const qs = params ? '?' + new URLSearchParams(params as Record<string, string>) : '';
    const data = await this.request<unknown>(`post${qs}`);
    return this.parse(z.array(PostSchema), data, 'Post[]');
  }

  /** Fetch a single post item by ID. */
  async getPost(id: string): Promise<Post> {
    const data = await this.request<unknown>(`post/${id}`);
    return this.parse(PostSchema, data, 'Post');
  }

  /** Create a new post item. */
  async createPost(data: Omit<Post, keyof PlatoItem>): Promise<Post> {
    const result = await this.request<unknown>('post', {
      method: 'POST',
      body: JSON.stringify(data),
    });
    return this.parse(PostSchema, result, 'Post');
  }

  /** Update an existing post item. */
  async updatePost(id: string, data: Partial<Omit<Post, keyof PlatoItem>>): Promise<Post> {
    const result = await this.request<unknown>(`post/${id}`, {
      method: 'PUT',
      body: JSON.stringify(data),
    });
    return this.parse(PostSchema, result, 'Post');
  }

  /** Delete a post item. */
  async deletePost(id: string): Promise<void> {
    await this.request(`post/${id}`, { method: 'DELETE' });
  }
}
