// Generated by @platoorg/zod-client — do not edit manually
// Namespace: website · public: true
// Schema count: 3

import { z } from 'zod';

// ── Base ─────────────────────────────────────────────────────
export const PlatoItemSchema = z.object({
  id: z.string(),
  created_at: z.string().optional(),
  updated_at: z.string().optional(),
});
export type PlatoItem = z.infer<typeof PlatoItemSchema>;

// ── Media ──────────────────────────────────────────────────
/** Single resized variant generated at upload time. */
export const MediaVariantSchema = z.object({
  url: z.string(),
  width: z.number(),
});
export type MediaVariant = z.infer<typeof MediaVariantSchema>;

/**
 * Stored value for a `media` field. The new shape carries widths inside
 * each variant entry; the legacy shape used variant URL strings and is
 * tolerated here via z.union (mediaSrcset() will skip string variants
 * since their widths are unknown at runtime).
 */
export const MediaValueSchema = z.object({
  url: z.string(),
  width: z.number().optional(),
  height: z.number().optional(),
  variants: z.record(z.string(), z.union([MediaVariantSchema, z.string()])).optional(),
});
export type MediaValue = z.infer<typeof MediaValueSchema>;

/**
 * On-the-wire schema for a `media` field. The server returns:
 *   - a plain URL string when no variants are configured on the field
 *     (or for plain-string assets uploaded before responsive media existed), or
 *   - a MediaValue object when variants are configured.
 * mediaSrcset() accepts either form.
 */
export const MediaFieldSchema = z.union([MediaValueSchema, z.string()]);

/** Result of mediaSrcset(). Spread into <img {...result} alt="..." />. */
export interface MediaSrcsetResult {
  src: string;
  srcset?: string;
  sizes?: string;
  width?: number;
  height?: number;
}

/**
 * Build src / srcset / sizes attributes from a Plato media value.
 * Returns null when no usable URL is present.
 */
export function mediaSrcset(
  value: MediaValue | string | null | undefined,
  sizes?: string,
): MediaSrcsetResult | null {
  if (value == null) return null;
  if (typeof value === 'string') return value ? { src: value } : null;
  if (!value.url && !value.variants) return null;

  const entries: Array<{ url: string; width: number }> = [];
  let maxWidth = 0;
  if (value.variants) {
    for (const raw of Object.values(value.variants)) {
      if (!raw || typeof raw !== 'object') continue;
      const { url, width } = raw;
      if (!url || !width || width <= 0) continue;
      entries.push({ url, width });
      if (width > maxWidth) maxWidth = width;
    }
  }

  const dims: { width?: number; height?: number } = {};
  if (typeof value.width === 'number')  dims.width  = value.width;
  if (typeof value.height === 'number') dims.height = value.height;

  if (entries.length === 0) {
    return value.url ? { src: value.url, ...dims } : null;
  }

  if (value.url) {
    const w = (value.width ?? 0) > maxWidth ? value.width! : maxWidth + 1;
    entries.push({ url: value.url, width: w });
  }
  entries.sort((a, b) => a.width - b.width);

  const srcset = entries.map(e => `${e.url} ${e.width}w`).join(', ');
  return {
    src: value.url || entries[entries.length - 1].url,
    srcset,
    ...(sizes ? { sizes } : {}),
    ...dims,
  };
}

/** singleton */
export const HomepageSchema = PlatoItemSchema.extend({
  hero_title: z.string(),
  hero_subtitle: z.string().optional(),
  hero_image: MediaFieldSchema.optional(),
});
export type Homepage = z.infer<typeof HomepageSchema>;

/** collection */
export const PostSchema = PlatoItemSchema.extend({
  title: z.string(),
  body: z.string().optional(),
  published_at: z.string().optional(), // ISO 8601 date string
  tags: z.array(z.string()).optional(), // IDs of related items
});
export type Post = z.infer<typeof PostSchema>;

/** collection */
export const ArticleSchema = PlatoItemSchema.extend({
  title: z.string(),
  body: z.string().optional(),
  meta_description: z.string().optional(),
  cover_image: MediaFieldSchema.optional(),
  og_title: z.string().optional(),
  author: z.string().optional(),
});
export type Article = z.infer<typeof ArticleSchema>;

export interface PostParams {
  title?: string;
  body?: string;
  published_at?: string;
  tags?: string;
}

export interface ArticleParams {
  title?: string;
  body?: string;
  meta_description?: string;
  cover_image?: string;
  og_title?: string;
  author?: string;
}

// ── Client ──────────────────────────────────────────────────
export class PlatoClient {
  constructor(
    private readonly baseUrl: string,
    private readonly namespace: string,
    private readonly apiKey?: string,
  ) {}

  private headers(): Record<string, string> {
    const h: Record<string, string> = { 'Content-Type': 'application/json' };
    if (this.apiKey) h['Authorization'] = `Bearer ${this.apiKey}`;
    return h;
  }

  private async request<T>(path: string, init?: RequestInit): Promise<T> {
    const url = `${this.baseUrl}/api/namespaces/${this.namespace}/content/${path}`;
    const res  = await fetch(url, { ...init, headers: this.headers() });
    if (!res.ok) {
      throw new Error(`Plato ${init?.method ?? 'GET'} ${url}: ${res.status} ${res.statusText}`);
    }
    return res.json() as Promise<T>;
  }

  private parse<T>(schema: z.ZodType<T>, data: unknown, label: string): T {
    try {
      return schema.parse(data);
    } catch (err) {
      if (err instanceof z.ZodError) {
        const issues = err.errors.map(e => `${e.path.join('.')||'root'}: ${e.message}`).join('; ');
        throw new Error(`PlatoParseError [${label}]: ${issues}`);
      }
      throw err;
    }
  }

  // ── homepage (singleton) ────────────────────────────────────
  /** Fetch the homepage singleton. */
  async getHomepage(): Promise<Homepage | null> {
    const data = await this.request<unknown>('homepage');
    const items = this.parse(z.array(HomepageSchema), data, 'Homepage[]');
    return items[0] ?? null;
  }

  /** Update the homepage singleton. */
  async updateHomepage(data: Partial<Omit<Homepage, keyof PlatoItem>>): Promise<Homepage> {
    const item = await this.getHomepage();
    if (!item) throw new Error('homepage singleton not found');
    const result = await this.request<unknown>(`homepage/${item.id}`, {
      method: 'PUT',
      body: JSON.stringify(data),
    });
    return this.parse(HomepageSchema, result, 'Homepage');
  }

  // ── post (collection) ────────────────────────────────────────
  /** List post items. Pass filter params as `{ field: value }`. */
  async listPost(params?: PostParams): Promise<Post[]> {
    const qs = params ? '?' + new URLSearchParams(params as Record<string, string>) : '';
    const data = await this.request<unknown>(`post${qs}`);
    return this.parse(z.array(PostSchema), data, 'Post[]');
  }

  /** Fetch a single post item by ID. */
  async getPost(id: string): Promise<Post> {
    const data = await this.request<unknown>(`post/${id}`);
    return this.parse(PostSchema, data, 'Post');
  }

  /** Create a new post item. */
  async createPost(data: Omit<Post, keyof PlatoItem>): Promise<Post> {
    const result = await this.request<unknown>('post', {
      method: 'POST',
      body: JSON.stringify(data),
    });
    return this.parse(PostSchema, result, 'Post');
  }

  /** Update an existing post item. */
  async updatePost(id: string, data: Partial<Omit<Post, keyof PlatoItem>>): Promise<Post> {
    const result = await this.request<unknown>(`post/${id}`, {
      method: 'PUT',
      body: JSON.stringify(data),
    });
    return this.parse(PostSchema, result, 'Post');
  }

  /** Delete a post item. */
  async deletePost(id: string): Promise<void> {
    await this.request(`post/${id}`, { method: 'DELETE' });
  }

  // ── article (collection) ─────────────────────────────────────
  /** List article items. Pass filter params as `{ field: value }`. */
  async listArticle(params?: ArticleParams): Promise<Article[]> {
    const qs = params ? '?' + new URLSearchParams(params as Record<string, string>) : '';
    const data = await this.request<unknown>(`article${qs}`);
    return this.parse(z.array(ArticleSchema), data, 'Article[]');
  }

  /** Fetch a single article item by ID. */
  async getArticle(id: string): Promise<Article> {
    const data = await this.request<unknown>(`article/${id}`);
    return this.parse(ArticleSchema, data, 'Article');
  }

  /** Create a new article item. */
  async createArticle(data: Omit<Article, keyof PlatoItem>): Promise<Article> {
    const result = await this.request<unknown>('article', {
      method: 'POST',
      body: JSON.stringify(data),
    });
    return this.parse(ArticleSchema, result, 'Article');
  }

  /** Update an existing article item. */
  async updateArticle(id: string, data: Partial<Omit<Article, keyof PlatoItem>>): Promise<Article> {
    const result = await this.request<unknown>(`article/${id}`, {
      method: 'PUT',
      body: JSON.stringify(data),
    });
    return this.parse(ArticleSchema, result, 'Article');
  }

  /** Delete a article item. */
  async deleteArticle(id: string): Promise<void> {
    await this.request(`article/${id}`, { method: 'DELETE' });
  }
}
